// Code generated by ent, DO NOT EDIT.

package repositoryrelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repositoryrelease type in the database.
	Label = "repository_release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCommitSha holds the string denoting the commit_sha field in the database.
	FieldCommitSha = "commit_sha"
	// FieldTreeSha holds the string denoting the tree_sha field in the database.
	FieldTreeSha = "tree_sha"
	// FieldSum holds the string denoting the sum field in the database.
	FieldSum = "sum"
	// FieldArchiveSize holds the string denoting the archive_size field in the database.
	FieldArchiveSize = "archive_size"
	// FieldReleaseInfo holds the string denoting the release_info field in the database.
	FieldReleaseInfo = "release_info"
	// FieldCommitTime holds the string denoting the commit_time field in the database.
	FieldCommitTime = "commit_time"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRepository holds the string denoting the repository edge name in mutations.
	EdgeRepository = "repository"
	// EdgeCurrentForRepository holds the string denoting the current_for_repository edge name in mutations.
	EdgeCurrentForRepository = "current_for_repository"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// Table holds the table name of the repositoryrelease in the database.
	Table = "repository_releases"
	// RepositoryTable is the table that holds the repository relation/edge.
	RepositoryTable = "repository_releases"
	// RepositoryInverseTable is the table name for the Repository entity.
	// It exists in this package in order to avoid circular dependency with the "repository" package.
	RepositoryInverseTable = "repositories"
	// RepositoryColumn is the table column denoting the repository relation/edge.
	RepositoryColumn = "repository_id"
	// CurrentForRepositoryTable is the table that holds the current_for_repository relation/edge.
	CurrentForRepositoryTable = "repositories"
	// CurrentForRepositoryInverseTable is the table name for the Repository entity.
	// It exists in this package in order to avoid circular dependency with the "repository" package.
	CurrentForRepositoryInverseTable = "repositories"
	// CurrentForRepositoryColumn is the table column denoting the current_for_repository relation/edge.
	CurrentForRepositoryColumn = "current_release_id"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "repository_release_members"
	// MembersInverseTable is the table name for the RepositoryReleaseMember entity.
	// It exists in this package in order to avoid circular dependency with the "repositoryreleasemember" package.
	MembersInverseTable = "repository_release_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "release_id"
)

// Columns holds all SQL columns for repositoryrelease fields.
var Columns = []string{
	FieldID,
	FieldRepositoryID,
	FieldVersion,
	FieldCommitSha,
	FieldTreeSha,
	FieldSum,
	FieldArchiveSize,
	FieldReleaseInfo,
	FieldCommitTime,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// CommitShaValidator is a validator for the "commit_sha" field. It is called by the builders before save.
	CommitShaValidator func(string) error
	// TreeShaValidator is a validator for the "tree_sha" field. It is called by the builders before save.
	TreeShaValidator func(string) error
	// SumValidator is a validator for the "sum" field. It is called by the builders before save.
	SumValidator func(string) error
	// ArchiveSizeValidator is a validator for the "archive_size" field. It is called by the builders before save.
	ArchiveSizeValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RepositoryRelease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCommitSha orders the results by the commit_sha field.
func ByCommitSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitSha, opts...).ToFunc()
}

// ByTreeSha orders the results by the tree_sha field.
func ByTreeSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTreeSha, opts...).ToFunc()
}

// BySum orders the results by the sum field.
func BySum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSum, opts...).ToFunc()
}

// ByArchiveSize orders the results by the archive_size field.
func ByArchiveSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchiveSize, opts...).ToFunc()
}

// ByCommitTime orders the results by the commit_time field.
func ByCommitTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitTime, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRepositoryField orders the results by repository field.
func ByRepositoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepositoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByCurrentForRepositoryCount orders the results by current_for_repository count.
func ByCurrentForRepositoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCurrentForRepositoryStep(), opts...)
	}
}

// ByCurrentForRepository orders the results by current_for_repository terms.
func ByCurrentForRepository(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentForRepositoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRepositoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepositoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
	)
}
func newCurrentForRepositoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentForRepositoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, CurrentForRepositoryTable, CurrentForRepositoryColumn),
	)
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
