// Code generated by ent, DO NOT EDIT.

package repositoryrelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldID, id))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldRepositoryID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldVersion, v))
}

// CommitSha applies equality check predicate on the "commit_sha" field. It's identical to CommitShaEQ.
func CommitSha(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCommitSha, v))
}

// TreeSha applies equality check predicate on the "tree_sha" field. It's identical to TreeShaEQ.
func TreeSha(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldTreeSha, v))
}

// Sum applies equality check predicate on the "sum" field. It's identical to SumEQ.
func Sum(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldSum, v))
}

// ArchiveSize applies equality check predicate on the "archive_size" field. It's identical to ArchiveSizeEQ.
func ArchiveSize(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldArchiveSize, v))
}

// ReleaseInfo applies equality check predicate on the "release_info" field. It's identical to ReleaseInfoEQ.
func ReleaseInfo(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldReleaseInfo, v))
}

// CommitTime applies equality check predicate on the "commit_time" field. It's identical to CommitTimeEQ.
func CommitTime(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCommitTime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContainsFold(FieldVersion, v))
}

// CommitShaEQ applies the EQ predicate on the "commit_sha" field.
func CommitShaEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCommitSha, v))
}

// CommitShaNEQ applies the NEQ predicate on the "commit_sha" field.
func CommitShaNEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldCommitSha, v))
}

// CommitShaIn applies the In predicate on the "commit_sha" field.
func CommitShaIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldCommitSha, vs...))
}

// CommitShaNotIn applies the NotIn predicate on the "commit_sha" field.
func CommitShaNotIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldCommitSha, vs...))
}

// CommitShaGT applies the GT predicate on the "commit_sha" field.
func CommitShaGT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldCommitSha, v))
}

// CommitShaGTE applies the GTE predicate on the "commit_sha" field.
func CommitShaGTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldCommitSha, v))
}

// CommitShaLT applies the LT predicate on the "commit_sha" field.
func CommitShaLT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldCommitSha, v))
}

// CommitShaLTE applies the LTE predicate on the "commit_sha" field.
func CommitShaLTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldCommitSha, v))
}

// CommitShaContains applies the Contains predicate on the "commit_sha" field.
func CommitShaContains(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContains(FieldCommitSha, v))
}

// CommitShaHasPrefix applies the HasPrefix predicate on the "commit_sha" field.
func CommitShaHasPrefix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasPrefix(FieldCommitSha, v))
}

// CommitShaHasSuffix applies the HasSuffix predicate on the "commit_sha" field.
func CommitShaHasSuffix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasSuffix(FieldCommitSha, v))
}

// CommitShaEqualFold applies the EqualFold predicate on the "commit_sha" field.
func CommitShaEqualFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEqualFold(FieldCommitSha, v))
}

// CommitShaContainsFold applies the ContainsFold predicate on the "commit_sha" field.
func CommitShaContainsFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContainsFold(FieldCommitSha, v))
}

// TreeShaEQ applies the EQ predicate on the "tree_sha" field.
func TreeShaEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldTreeSha, v))
}

// TreeShaNEQ applies the NEQ predicate on the "tree_sha" field.
func TreeShaNEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldTreeSha, v))
}

// TreeShaIn applies the In predicate on the "tree_sha" field.
func TreeShaIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldTreeSha, vs...))
}

// TreeShaNotIn applies the NotIn predicate on the "tree_sha" field.
func TreeShaNotIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldTreeSha, vs...))
}

// TreeShaGT applies the GT predicate on the "tree_sha" field.
func TreeShaGT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldTreeSha, v))
}

// TreeShaGTE applies the GTE predicate on the "tree_sha" field.
func TreeShaGTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldTreeSha, v))
}

// TreeShaLT applies the LT predicate on the "tree_sha" field.
func TreeShaLT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldTreeSha, v))
}

// TreeShaLTE applies the LTE predicate on the "tree_sha" field.
func TreeShaLTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldTreeSha, v))
}

// TreeShaContains applies the Contains predicate on the "tree_sha" field.
func TreeShaContains(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContains(FieldTreeSha, v))
}

// TreeShaHasPrefix applies the HasPrefix predicate on the "tree_sha" field.
func TreeShaHasPrefix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasPrefix(FieldTreeSha, v))
}

// TreeShaHasSuffix applies the HasSuffix predicate on the "tree_sha" field.
func TreeShaHasSuffix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasSuffix(FieldTreeSha, v))
}

// TreeShaEqualFold applies the EqualFold predicate on the "tree_sha" field.
func TreeShaEqualFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEqualFold(FieldTreeSha, v))
}

// TreeShaContainsFold applies the ContainsFold predicate on the "tree_sha" field.
func TreeShaContainsFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContainsFold(FieldTreeSha, v))
}

// SumEQ applies the EQ predicate on the "sum" field.
func SumEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldSum, v))
}

// SumNEQ applies the NEQ predicate on the "sum" field.
func SumNEQ(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldSum, v))
}

// SumIn applies the In predicate on the "sum" field.
func SumIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldSum, vs...))
}

// SumNotIn applies the NotIn predicate on the "sum" field.
func SumNotIn(vs ...string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldSum, vs...))
}

// SumGT applies the GT predicate on the "sum" field.
func SumGT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldSum, v))
}

// SumGTE applies the GTE predicate on the "sum" field.
func SumGTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldSum, v))
}

// SumLT applies the LT predicate on the "sum" field.
func SumLT(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldSum, v))
}

// SumLTE applies the LTE predicate on the "sum" field.
func SumLTE(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldSum, v))
}

// SumContains applies the Contains predicate on the "sum" field.
func SumContains(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContains(FieldSum, v))
}

// SumHasPrefix applies the HasPrefix predicate on the "sum" field.
func SumHasPrefix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasPrefix(FieldSum, v))
}

// SumHasSuffix applies the HasSuffix predicate on the "sum" field.
func SumHasSuffix(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldHasSuffix(FieldSum, v))
}

// SumEqualFold applies the EqualFold predicate on the "sum" field.
func SumEqualFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEqualFold(FieldSum, v))
}

// SumContainsFold applies the ContainsFold predicate on the "sum" field.
func SumContainsFold(v string) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldContainsFold(FieldSum, v))
}

// ArchiveSizeEQ applies the EQ predicate on the "archive_size" field.
func ArchiveSizeEQ(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldArchiveSize, v))
}

// ArchiveSizeNEQ applies the NEQ predicate on the "archive_size" field.
func ArchiveSizeNEQ(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldArchiveSize, v))
}

// ArchiveSizeIn applies the In predicate on the "archive_size" field.
func ArchiveSizeIn(vs ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldArchiveSize, vs...))
}

// ArchiveSizeNotIn applies the NotIn predicate on the "archive_size" field.
func ArchiveSizeNotIn(vs ...int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldArchiveSize, vs...))
}

// ArchiveSizeGT applies the GT predicate on the "archive_size" field.
func ArchiveSizeGT(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldArchiveSize, v))
}

// ArchiveSizeGTE applies the GTE predicate on the "archive_size" field.
func ArchiveSizeGTE(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldArchiveSize, v))
}

// ArchiveSizeLT applies the LT predicate on the "archive_size" field.
func ArchiveSizeLT(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldArchiveSize, v))
}

// ArchiveSizeLTE applies the LTE predicate on the "archive_size" field.
func ArchiveSizeLTE(v int64) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldArchiveSize, v))
}

// ReleaseInfoEQ applies the EQ predicate on the "release_info" field.
func ReleaseInfoEQ(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldReleaseInfo, v))
}

// ReleaseInfoNEQ applies the NEQ predicate on the "release_info" field.
func ReleaseInfoNEQ(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldReleaseInfo, v))
}

// ReleaseInfoIn applies the In predicate on the "release_info" field.
func ReleaseInfoIn(vs ...[]byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldReleaseInfo, vs...))
}

// ReleaseInfoNotIn applies the NotIn predicate on the "release_info" field.
func ReleaseInfoNotIn(vs ...[]byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldReleaseInfo, vs...))
}

// ReleaseInfoGT applies the GT predicate on the "release_info" field.
func ReleaseInfoGT(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldReleaseInfo, v))
}

// ReleaseInfoGTE applies the GTE predicate on the "release_info" field.
func ReleaseInfoGTE(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldReleaseInfo, v))
}

// ReleaseInfoLT applies the LT predicate on the "release_info" field.
func ReleaseInfoLT(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldReleaseInfo, v))
}

// ReleaseInfoLTE applies the LTE predicate on the "release_info" field.
func ReleaseInfoLTE(v []byte) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldReleaseInfo, v))
}

// CommitTimeEQ applies the EQ predicate on the "commit_time" field.
func CommitTimeEQ(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCommitTime, v))
}

// CommitTimeNEQ applies the NEQ predicate on the "commit_time" field.
func CommitTimeNEQ(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldCommitTime, v))
}

// CommitTimeIn applies the In predicate on the "commit_time" field.
func CommitTimeIn(vs ...time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldCommitTime, vs...))
}

// CommitTimeNotIn applies the NotIn predicate on the "commit_time" field.
func CommitTimeNotIn(vs ...time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldCommitTime, vs...))
}

// CommitTimeGT applies the GT predicate on the "commit_time" field.
func CommitTimeGT(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldCommitTime, v))
}

// CommitTimeGTE applies the GTE predicate on the "commit_time" field.
func CommitTimeGTE(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldCommitTime, v))
}

// CommitTimeLT applies the LT predicate on the "commit_time" field.
func CommitTimeLT(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldCommitTime, v))
}

// CommitTimeLTE applies the LTE predicate on the "commit_time" field.
func CommitTimeLTE(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldCommitTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRepository applies the HasEdge predicate on the "repository" edge.
func HasRepository() predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoryWith applies the HasEdge predicate on the "repository" edge with a given conditions (other predicates).
func HasRepositoryWith(preds ...predicate.Repository) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := newRepositoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrentForRepository applies the HasEdge predicate on the "current_for_repository" edge.
func HasCurrentForRepository() predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, CurrentForRepositoryTable, CurrentForRepositoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrentForRepositoryWith applies the HasEdge predicate on the "current_for_repository" edge with a given conditions (other predicates).
func HasCurrentForRepositoryWith(preds ...predicate.Repository) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := newCurrentForRepositoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.RepositoryReleaseMember) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepositoryRelease) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepositoryRelease) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepositoryRelease) predicate.RepositoryRelease {
	return predicate.RepositoryRelease(sql.NotPredicates(p))
}
