version: 2
project_name: skillsgo-registry

before:
  hooks:
    - go mod download
env:
- CGO_ENABLED=0
- GOPROXY=https://proxy.golang.org

builds:
- id: builds
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  main: cmd/registry/main.go
  binary: skillsgo-registry
  ldflags:
    - -X "github.com/skillsgo/skillsgo/registry/pkg/build.version={{ .Tag }}"
    - -X "github.com/skillsgo/skillsgo/registry/pkg/build.buildDate={{ .Env.DATE }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
