version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /registry
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: weekly
