// Code generated by ent, DO NOT EDIT.

package repositoryreleasemember

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repositoryreleasemember type in the database.
	Label = "repository_release_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReleaseID holds the string denoting the release_id field in the database.
	FieldReleaseID = "release_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSkillPath holds the string denoting the skill_path field in the database.
	FieldSkillPath = "skill_path"
	// FieldTreeSha holds the string denoting the tree_sha field in the database.
	FieldTreeSha = "tree_sha"
	// EdgeRelease holds the string denoting the release edge name in mutations.
	EdgeRelease = "release"
	// Table holds the table name of the repositoryreleasemember in the database.
	Table = "repository_release_members"
	// ReleaseTable is the table that holds the release relation/edge.
	ReleaseTable = "repository_release_members"
	// ReleaseInverseTable is the table name for the RepositoryRelease entity.
	// It exists in this package in order to avoid circular dependency with the "repositoryrelease" package.
	ReleaseInverseTable = "repository_releases"
	// ReleaseColumn is the table column denoting the release relation/edge.
	ReleaseColumn = "release_id"
)

// Columns holds all SQL columns for repositoryreleasemember fields.
var Columns = []string{
	FieldID,
	FieldReleaseID,
	FieldName,
	FieldSkillPath,
	FieldTreeSha,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SkillPathValidator is a validator for the "skill_path" field. It is called by the builders before save.
	SkillPathValidator func(string) error
	// TreeShaValidator is a validator for the "tree_sha" field. It is called by the builders before save.
	TreeShaValidator func(string) error
)

// OrderOption defines the ordering options for the RepositoryReleaseMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReleaseID orders the results by the release_id field.
func ByReleaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySkillPath orders the results by the skill_path field.
func BySkillPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillPath, opts...).ToFunc()
}

// ByTreeSha orders the results by the tree_sha field.
func ByTreeSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTreeSha, opts...).ToFunc()
}

// ByReleaseField orders the results by release field.
func ByReleaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReleaseStep(), sql.OrderByField(field, opts...))
	}
}
func newReleaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReleaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReleaseTable, ReleaseColumn),
	)
}
