// Code generated by ent, DO NOT EDIT.

package skill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSourceHost holds the string denoting the source_host field in the database.
	FieldSourceHost = "source_host"
	// FieldRepository holds the string denoting the repository field in the database.
	FieldRepository = "repository"
	// FieldSkillPath holds the string denoting the skill_path field in the database.
	FieldSkillPath = "skill_path"
	// FieldLatestVersion holds the string denoting the latest_version field in the database.
	FieldLatestVersion = "latest_version"
	// FieldDiscoverable holds the string denoting the discoverable field in the database.
	FieldDiscoverable = "discoverable"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSourceRepository holds the string denoting the source_repository edge name in mutations.
	EdgeSourceRepository = "source_repository"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// EdgeInstallEvents holds the string denoting the install_events edge name in mutations.
	EdgeInstallEvents = "install_events"
	// EdgeHourlyStats holds the string denoting the hourly_stats edge name in mutations.
	EdgeHourlyStats = "hourly_stats"
	// InstallEventFieldID holds the string denoting the ID field of the InstallEvent.
	InstallEventFieldID = "event_id"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// SourceRepositoryTable is the table that holds the source_repository relation/edge.
	SourceRepositoryTable = "skills"
	// SourceRepositoryInverseTable is the table name for the Repository entity.
	// It exists in this package in order to avoid circular dependency with the "repository" package.
	SourceRepositoryInverseTable = "repositories"
	// SourceRepositoryColumn is the table column denoting the source_repository relation/edge.
	SourceRepositoryColumn = "repository_id"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "skill_versions"
	// VersionsInverseTable is the table name for the SkillVersion entity.
	// It exists in this package in order to avoid circular dependency with the "skillversion" package.
	VersionsInverseTable = "skill_versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "skill_id"
	// InstallEventsTable is the table that holds the install_events relation/edge.
	InstallEventsTable = "skill_install_events"
	// InstallEventsInverseTable is the table name for the InstallEvent entity.
	// It exists in this package in order to avoid circular dependency with the "installevent" package.
	InstallEventsInverseTable = "skill_install_events"
	// InstallEventsColumn is the table column denoting the install_events relation/edge.
	InstallEventsColumn = "skill_id"
	// HourlyStatsTable is the table that holds the hourly_stats relation/edge.
	HourlyStatsTable = "skill_hourly_stats"
	// HourlyStatsInverseTable is the table name for the SkillHourlyStat entity.
	// It exists in this package in order to avoid circular dependency with the "skillhourlystat" package.
	HourlyStatsInverseTable = "skill_hourly_stats"
	// HourlyStatsColumn is the table column denoting the hourly_stats relation/edge.
	HourlyStatsColumn = "skill_id"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldSkillID,
	FieldRepositoryID,
	FieldName,
	FieldDescription,
	FieldSourceHost,
	FieldRepository,
	FieldSkillPath,
	FieldLatestVersion,
	FieldDiscoverable,
	FieldVerified,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	SkillIDValidator func(string) error
	// DefaultDiscoverable holds the default value on creation for the "discoverable" field.
	DefaultDiscoverable bool
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Skill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySourceHost orders the results by the source_host field.
func BySourceHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceHost, opts...).ToFunc()
}

// ByRepository orders the results by the repository field.
func ByRepository(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepository, opts...).ToFunc()
}

// BySkillPath orders the results by the skill_path field.
func BySkillPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillPath, opts...).ToFunc()
}

// ByLatestVersion orders the results by the latest_version field.
func ByLatestVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestVersion, opts...).ToFunc()
}

// ByDiscoverable orders the results by the discoverable field.
func ByDiscoverable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscoverable, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySourceRepositoryField orders the results by source_repository field.
func BySourceRepositoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceRepositoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInstallEventsCount orders the results by install_events count.
func ByInstallEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInstallEventsStep(), opts...)
	}
}

// ByInstallEvents orders the results by install_events terms.
func ByInstallEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstallEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHourlyStatsCount orders the results by hourly_stats count.
func ByHourlyStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHourlyStatsStep(), opts...)
	}
}

// ByHourlyStats orders the results by hourly_stats terms.
func ByHourlyStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHourlyStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSourceRepositoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceRepositoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceRepositoryTable, SourceRepositoryColumn),
	)
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
	)
}
func newInstallEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstallEventsInverseTable, InstallEventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InstallEventsTable, InstallEventsColumn),
	)
}
func newHourlyStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HourlyStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HourlyStatsTable, HourlyStatsColumn),
	)
}
