// Code generated by ent, DO NOT EDIT.

package repository

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldID, id))
}

// SourceHost applies equality check predicate on the "source_host" field. It's identical to SourceHostEQ.
func SourceHost(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceHost, v))
}

// RepositoryPath applies equality check predicate on the "repository_path" field. It's identical to RepositoryPathEQ.
func RepositoryPath(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldRepositoryPath, v))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldRepositoryID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// Stars applies equality check predicate on the "stars" field. It's identical to StarsEQ.
func Stars(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldStars, v))
}

// SourceMetadataEtag applies equality check predicate on the "source_metadata_etag" field. It's identical to SourceMetadataEtagEQ.
func SourceMetadataEtag(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataEtag, v))
}

// SourceMetadataCheckedAt applies equality check predicate on the "source_metadata_checked_at" field. It's identical to SourceMetadataCheckedAtEQ.
func SourceMetadataCheckedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataRetryAt applies equality check predicate on the "source_metadata_retry_at" field. It's identical to SourceMetadataRetryAtEQ.
func SourceMetadataRetryAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataRetryAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceHostEQ applies the EQ predicate on the "source_host" field.
func SourceHostEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceHost, v))
}

// SourceHostNEQ applies the NEQ predicate on the "source_host" field.
func SourceHostNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldSourceHost, v))
}

// SourceHostIn applies the In predicate on the "source_host" field.
func SourceHostIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldSourceHost, vs...))
}

// SourceHostNotIn applies the NotIn predicate on the "source_host" field.
func SourceHostNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldSourceHost, vs...))
}

// SourceHostGT applies the GT predicate on the "source_host" field.
func SourceHostGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldSourceHost, v))
}

// SourceHostGTE applies the GTE predicate on the "source_host" field.
func SourceHostGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldSourceHost, v))
}

// SourceHostLT applies the LT predicate on the "source_host" field.
func SourceHostLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldSourceHost, v))
}

// SourceHostLTE applies the LTE predicate on the "source_host" field.
func SourceHostLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldSourceHost, v))
}

// SourceHostContains applies the Contains predicate on the "source_host" field.
func SourceHostContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldSourceHost, v))
}

// SourceHostHasPrefix applies the HasPrefix predicate on the "source_host" field.
func SourceHostHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldSourceHost, v))
}

// SourceHostHasSuffix applies the HasSuffix predicate on the "source_host" field.
func SourceHostHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldSourceHost, v))
}

// SourceHostEqualFold applies the EqualFold predicate on the "source_host" field.
func SourceHostEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldSourceHost, v))
}

// SourceHostContainsFold applies the ContainsFold predicate on the "source_host" field.
func SourceHostContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldSourceHost, v))
}

// RepositoryPathEQ applies the EQ predicate on the "repository_path" field.
func RepositoryPathEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldRepositoryPath, v))
}

// RepositoryPathNEQ applies the NEQ predicate on the "repository_path" field.
func RepositoryPathNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldRepositoryPath, v))
}

// RepositoryPathIn applies the In predicate on the "repository_path" field.
func RepositoryPathIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldRepositoryPath, vs...))
}

// RepositoryPathNotIn applies the NotIn predicate on the "repository_path" field.
func RepositoryPathNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldRepositoryPath, vs...))
}

// RepositoryPathGT applies the GT predicate on the "repository_path" field.
func RepositoryPathGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldRepositoryPath, v))
}

// RepositoryPathGTE applies the GTE predicate on the "repository_path" field.
func RepositoryPathGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldRepositoryPath, v))
}

// RepositoryPathLT applies the LT predicate on the "repository_path" field.
func RepositoryPathLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldRepositoryPath, v))
}

// RepositoryPathLTE applies the LTE predicate on the "repository_path" field.
func RepositoryPathLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldRepositoryPath, v))
}

// RepositoryPathContains applies the Contains predicate on the "repository_path" field.
func RepositoryPathContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldRepositoryPath, v))
}

// RepositoryPathHasPrefix applies the HasPrefix predicate on the "repository_path" field.
func RepositoryPathHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldRepositoryPath, v))
}

// RepositoryPathHasSuffix applies the HasSuffix predicate on the "repository_path" field.
func RepositoryPathHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldRepositoryPath, v))
}

// RepositoryPathEqualFold applies the EqualFold predicate on the "repository_path" field.
func RepositoryPathEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldRepositoryPath, v))
}

// RepositoryPathContainsFold applies the ContainsFold predicate on the "repository_path" field.
func RepositoryPathContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldRepositoryPath, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDContains applies the Contains predicate on the "repository_id" field.
func RepositoryIDContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldRepositoryID, v))
}

// RepositoryIDHasPrefix applies the HasPrefix predicate on the "repository_id" field.
func RepositoryIDHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldRepositoryID, v))
}

// RepositoryIDHasSuffix applies the HasSuffix predicate on the "repository_id" field.
func RepositoryIDHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldRepositoryID, v))
}

// RepositoryIDEqualFold applies the EqualFold predicate on the "repository_id" field.
func RepositoryIDEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldRepositoryID, v))
}

// RepositoryIDContainsFold applies the ContainsFold predicate on the "repository_id" field.
func RepositoryIDContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldRepositoryID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldDescription, v))
}

// StarsEQ applies the EQ predicate on the "stars" field.
func StarsEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldStars, v))
}

// StarsNEQ applies the NEQ predicate on the "stars" field.
func StarsNEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldStars, v))
}

// StarsIn applies the In predicate on the "stars" field.
func StarsIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldStars, vs...))
}

// StarsNotIn applies the NotIn predicate on the "stars" field.
func StarsNotIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldStars, vs...))
}

// StarsGT applies the GT predicate on the "stars" field.
func StarsGT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldStars, v))
}

// StarsGTE applies the GTE predicate on the "stars" field.
func StarsGTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldStars, v))
}

// StarsLT applies the LT predicate on the "stars" field.
func StarsLT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldStars, v))
}

// StarsLTE applies the LTE predicate on the "stars" field.
func StarsLTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldStars, v))
}

// SourceMetadataEtagEQ applies the EQ predicate on the "source_metadata_etag" field.
func SourceMetadataEtagEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagNEQ applies the NEQ predicate on the "source_metadata_etag" field.
func SourceMetadataEtagNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagIn applies the In predicate on the "source_metadata_etag" field.
func SourceMetadataEtagIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldSourceMetadataEtag, vs...))
}

// SourceMetadataEtagNotIn applies the NotIn predicate on the "source_metadata_etag" field.
func SourceMetadataEtagNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldSourceMetadataEtag, vs...))
}

// SourceMetadataEtagGT applies the GT predicate on the "source_metadata_etag" field.
func SourceMetadataEtagGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagGTE applies the GTE predicate on the "source_metadata_etag" field.
func SourceMetadataEtagGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagLT applies the LT predicate on the "source_metadata_etag" field.
func SourceMetadataEtagLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagLTE applies the LTE predicate on the "source_metadata_etag" field.
func SourceMetadataEtagLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagContains applies the Contains predicate on the "source_metadata_etag" field.
func SourceMetadataEtagContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagHasPrefix applies the HasPrefix predicate on the "source_metadata_etag" field.
func SourceMetadataEtagHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagHasSuffix applies the HasSuffix predicate on the "source_metadata_etag" field.
func SourceMetadataEtagHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagIsNil applies the IsNil predicate on the "source_metadata_etag" field.
func SourceMetadataEtagIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldSourceMetadataEtag))
}

// SourceMetadataEtagNotNil applies the NotNil predicate on the "source_metadata_etag" field.
func SourceMetadataEtagNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldSourceMetadataEtag))
}

// SourceMetadataEtagEqualFold applies the EqualFold predicate on the "source_metadata_etag" field.
func SourceMetadataEtagEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldSourceMetadataEtag, v))
}

// SourceMetadataEtagContainsFold applies the ContainsFold predicate on the "source_metadata_etag" field.
func SourceMetadataEtagContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldSourceMetadataEtag, v))
}

// SourceMetadataCheckedAtEQ applies the EQ predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtNEQ applies the NEQ predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtIn applies the In predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldSourceMetadataCheckedAt, vs...))
}

// SourceMetadataCheckedAtNotIn applies the NotIn predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldSourceMetadataCheckedAt, vs...))
}

// SourceMetadataCheckedAtGT applies the GT predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtGTE applies the GTE predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtLT applies the LT predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtLTE applies the LTE predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldSourceMetadataCheckedAt, v))
}

// SourceMetadataCheckedAtIsNil applies the IsNil predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldSourceMetadataCheckedAt))
}

// SourceMetadataCheckedAtNotNil applies the NotNil predicate on the "source_metadata_checked_at" field.
func SourceMetadataCheckedAtNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldSourceMetadataCheckedAt))
}

// SourceMetadataRetryAtEQ applies the EQ predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtNEQ applies the NEQ predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtIn applies the In predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldSourceMetadataRetryAt, vs...))
}

// SourceMetadataRetryAtNotIn applies the NotIn predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldSourceMetadataRetryAt, vs...))
}

// SourceMetadataRetryAtGT applies the GT predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtGTE applies the GTE predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtLT applies the LT predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtLTE applies the LTE predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldSourceMetadataRetryAt, v))
}

// SourceMetadataRetryAtIsNil applies the IsNil predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldSourceMetadataRetryAt))
}

// SourceMetadataRetryAtNotNil applies the NotNil predicate on the "source_metadata_retry_at" field.
func SourceMetadataRetryAtNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldSourceMetadataRetryAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSkills applies the HasEdge predicate on the "skills" edge.
func HasSkills() predicate.Repository {
	return predicate.Repository(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SkillsTable, SkillsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillsWith applies the HasEdge predicate on the "skills" edge with a given conditions (other predicates).
func HasSkillsWith(preds ...predicate.Skill) predicate.Repository {
	return predicate.Repository(func(s *sql.Selector) {
		step := newSkillsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.NotPredicates(p))
}
