// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LocalizedDescription is the predicate function for localizeddescription builders.
type LocalizedDescription func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// RiskAssessment is the predicate function for riskassessment builders.
type RiskAssessment func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// SkillVersion is the predicate function for skillversion builders.
type SkillVersion func(*sql.Selector)
