// Code generated by ent, DO NOT EDIT.

package localizeddescription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the localizeddescription type in the database.
	Label = "localized_description"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceKind holds the string denoting the resource_kind field in the database.
	FieldResourceKind = "resource_kind"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSourceDigest holds the string denoting the source_digest field in the database.
	FieldSourceDigest = "source_digest"
	// FieldPromptVersion holds the string denoting the prompt_version field in the database.
	FieldPromptVersion = "prompt_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the localizeddescription in the database.
	Table = "localized_descriptions"
)

// Columns holds all SQL columns for localizeddescription fields.
var Columns = []string{
	FieldID,
	FieldResourceKind,
	FieldResourceID,
	FieldLocale,
	FieldDescription,
	FieldSourceDigest,
	FieldPromptVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ResourceKindValidator is a validator for the "resource_kind" field. It is called by the builders before save.
	ResourceKindValidator func(string) error
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	LocaleValidator func(string) error
	// SourceDigestValidator is a validator for the "source_digest" field. It is called by the builders before save.
	SourceDigestValidator func(string) error
	// PromptVersionValidator is a validator for the "prompt_version" field. It is called by the builders before save.
	PromptVersionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LocalizedDescription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceKind orders the results by the resource_kind field.
func ByResourceKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceKind, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySourceDigest orders the results by the source_digest field.
func BySourceDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDigest, opts...).ToFunc()
}

// ByPromptVersion orders the results by the prompt_version field.
func ByPromptVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
