// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SkillInstallEventsColumns holds the columns for the "skill_install_events" table.
	SkillInstallEventsColumns = []*schema.Column{
		{Name: "event_id", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "agents", Type: field.TypeString, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "scope", Type: field.TypeString},
		{Name: "cli_version", Type: field.TypeString},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "received_at", Type: field.TypeTime},
		{Name: "skill_id", Type: field.TypeInt64},
	}
	// SkillInstallEventsTable holds the schema information for the "skill_install_events" table.
	SkillInstallEventsTable = &schema.Table{
		Name:       "skill_install_events",
		Columns:    SkillInstallEventsColumns,
		PrimaryKey: []*schema.Column{SkillInstallEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_install_events_skills_install_events",
				Columns:    []*schema.Column{SkillInstallEventsColumns[7]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RepositoriesColumns holds the columns for the "repositories" table.
	RepositoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "source_host", Type: field.TypeString},
		{Name: "repository_path", Type: field.TypeString},
		{Name: "repository_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RepositoriesTable holds the schema information for the "repositories" table.
	RepositoriesTable = &schema.Table{
		Name:       "repositories",
		Columns:    RepositoriesColumns,
		PrimaryKey: []*schema.Column{RepositoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "repository_source_host_repository_path",
				Unique:  true,
				Columns: []*schema.Column{RepositoriesColumns[1], RepositoriesColumns[2]},
			},
			{
				Name:    "repository_repository_id",
				Unique:  true,
				Columns: []*schema.Column{RepositoriesColumns[3]},
			},
		},
	}
	// SkillRiskAssessmentsColumns holds the columns for the "skill_risk_assessments" table.
	SkillRiskAssessmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "level", Type: field.TypeString},
		{Name: "scanner_version", Type: field.TypeString},
		{Name: "evidence", Type: field.TypeString, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "skill_version_id", Type: field.TypeInt64},
	}
	// SkillRiskAssessmentsTable holds the schema information for the "skill_risk_assessments" table.
	SkillRiskAssessmentsTable = &schema.Table{
		Name:       "skill_risk_assessments",
		Columns:    SkillRiskAssessmentsColumns,
		PrimaryKey: []*schema.Column{SkillRiskAssessmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_risk_assessments_skill_versions_risk_assessments",
				Columns:    []*schema.Column{SkillRiskAssessmentsColumns[6]},
				RefColumns: []*schema.Column{SkillVersionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "skill_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "source_host", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "skill_path", Type: field.TypeString},
		{Name: "latest_version", Type: field.TypeString},
		{Name: "github_stars", Type: field.TypeInt64, Default: 0},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "repository_id", Type: field.TypeInt64},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skills_repositories_skills",
				Columns:    []*schema.Column{SkillsColumns[12]},
				RefColumns: []*schema.Column{RepositoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skill_skill_id",
				Unique:  true,
				Columns: []*schema.Column{SkillsColumns[1]},
			},
		},
	}
	// SkillHourlyStatsColumns holds the columns for the "skill_hourly_stats" table.
	SkillHourlyStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bucket", Type: field.TypeTime},
		{Name: "installs", Type: field.TypeInt64, Default: 0},
		{Name: "skill_id", Type: field.TypeInt64},
	}
	// SkillHourlyStatsTable holds the schema information for the "skill_hourly_stats" table.
	SkillHourlyStatsTable = &schema.Table{
		Name:       "skill_hourly_stats",
		Columns:    SkillHourlyStatsColumns,
		PrimaryKey: []*schema.Column{SkillHourlyStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_hourly_stats_skills_hourly_stats",
				Columns:    []*schema.Column{SkillHourlyStatsColumns[3]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skillhourlystat_skill_id_bucket",
				Unique:  true,
				Columns: []*schema.Column{SkillHourlyStatsColumns[3], SkillHourlyStatsColumns[1]},
			},
		},
	}
	// SkillStatsColumns holds the columns for the "skill_stats" table.
	SkillStatsColumns = []*schema.Column{
		{Name: "skill_id", Type: field.TypeInt64, Increment: true},
		{Name: "total_installs", Type: field.TypeInt64, Default: 0},
	}
	// SkillStatsTable holds the schema information for the "skill_stats" table.
	SkillStatsTable = &schema.Table{
		Name:       "skill_stats",
		Columns:    SkillStatsColumns,
		PrimaryKey: []*schema.Column{SkillStatsColumns[0]},
	}
	// SkillVersionsColumns holds the columns for the "skill_versions" table.
	SkillVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "version", Type: field.TypeString},
		{Name: "commit_sha", Type: field.TypeString},
		{Name: "tree_sha", Type: field.TypeString},
		{Name: "content_digest", Type: field.TypeString},
		{Name: "commit_time", Type: field.TypeTime},
		{Name: "archive_size", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "skill_id", Type: field.TypeInt64},
	}
	// SkillVersionsTable holds the schema information for the "skill_versions" table.
	SkillVersionsTable = &schema.Table{
		Name:       "skill_versions",
		Columns:    SkillVersionsColumns,
		PrimaryKey: []*schema.Column{SkillVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_versions_skills_versions",
				Columns:    []*schema.Column{SkillVersionsColumns[8]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skillversion_skill_id_version",
				Unique:  true,
				Columns: []*schema.Column{SkillVersionsColumns[8], SkillVersionsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SkillInstallEventsTable,
		RepositoriesTable,
		SkillRiskAssessmentsTable,
		SkillsTable,
		SkillHourlyStatsTable,
		SkillStatsTable,
		SkillVersionsTable,
	}
)

func init() {
	SkillInstallEventsTable.ForeignKeys[0].RefTable = SkillsTable
	SkillInstallEventsTable.Annotation = &entsql.Annotation{
		Table: "skill_install_events",
	}
	SkillRiskAssessmentsTable.ForeignKeys[0].RefTable = SkillVersionsTable
	SkillRiskAssessmentsTable.Annotation = &entsql.Annotation{
		Table: "skill_risk_assessments",
	}
	SkillsTable.ForeignKeys[0].RefTable = RepositoriesTable
	SkillHourlyStatsTable.ForeignKeys[0].RefTable = SkillsTable
	SkillVersionsTable.ForeignKeys[0].RefTable = SkillsTable
}
