// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LocalizedDescriptionsColumns holds the columns for the "localized_descriptions" table.
	LocalizedDescriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "resource_kind", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString},
		{Name: "locale", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "source_digest", Type: field.TypeString},
		{Name: "prompt_version", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// LocalizedDescriptionsTable holds the schema information for the "localized_descriptions" table.
	LocalizedDescriptionsTable = &schema.Table{
		Name:       "localized_descriptions",
		Columns:    LocalizedDescriptionsColumns,
		PrimaryKey: []*schema.Column{LocalizedDescriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "localizeddescription_resource_kind_resource_id_locale",
				Unique:  true,
				Columns: []*schema.Column{LocalizedDescriptionsColumns[1], LocalizedDescriptionsColumns[2], LocalizedDescriptionsColumns[3]},
			},
		},
	}
	// RepositoriesColumns holds the columns for the "repositories" table.
	RepositoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "source_host", Type: field.TypeString},
		{Name: "repository_path", Type: field.TypeString},
		{Name: "repository_id", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "stars", Type: field.TypeInt64, Default: 0},
		{Name: "source_metadata_etag", Type: field.TypeString, Nullable: true},
		{Name: "source_metadata_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "source_metadata_retry_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RepositoriesTable holds the schema information for the "repositories" table.
	RepositoriesTable = &schema.Table{
		Name:       "repositories",
		Columns:    RepositoriesColumns,
		PrimaryKey: []*schema.Column{RepositoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "repository_source_host_repository_path",
				Unique:  true,
				Columns: []*schema.Column{RepositoriesColumns[1], RepositoriesColumns[2]},
			},
			{
				Name:    "repository_repository_id",
				Unique:  true,
				Columns: []*schema.Column{RepositoriesColumns[3]},
			},
		},
	}
	// SkillRiskAssessmentsColumns holds the columns for the "skill_risk_assessments" table.
	SkillRiskAssessmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "level", Type: field.TypeString},
		{Name: "scanner_version", Type: field.TypeString},
		{Name: "evidence", Type: field.TypeString, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "skill_version_id", Type: field.TypeInt64},
	}
	// SkillRiskAssessmentsTable holds the schema information for the "skill_risk_assessments" table.
	SkillRiskAssessmentsTable = &schema.Table{
		Name:       "skill_risk_assessments",
		Columns:    SkillRiskAssessmentsColumns,
		PrimaryKey: []*schema.Column{SkillRiskAssessmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_risk_assessments_skill_versions_risk_assessments",
				Columns:    []*schema.Column{SkillRiskAssessmentsColumns[6]},
				RefColumns: []*schema.Column{SkillVersionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "source_host", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "skill_path", Type: field.TypeString},
		{Name: "latest_version", Type: field.TypeString},
		{Name: "discoverable", Type: field.TypeBool, Default: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "repository_id", Type: field.TypeInt64},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skills_repositories_skills",
				Columns:    []*schema.Column{SkillsColumns[11]},
				RefColumns: []*schema.Column{RepositoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skill_repository_id_name",
				Unique:  true,
				Columns: []*schema.Column{SkillsColumns[11], SkillsColumns[1]},
			},
		},
	}
	// SkillVersionsColumns holds the columns for the "skill_versions" table.
	SkillVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "version", Type: field.TypeString},
		{Name: "commit_sha", Type: field.TypeString},
		{Name: "tree_sha", Type: field.TypeString},
		{Name: "relative_path", Type: field.TypeString},
		{Name: "commit_time", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "skill_id", Type: field.TypeInt64},
	}
	// SkillVersionsTable holds the schema information for the "skill_versions" table.
	SkillVersionsTable = &schema.Table{
		Name:       "skill_versions",
		Columns:    SkillVersionsColumns,
		PrimaryKey: []*schema.Column{SkillVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_versions_skills_versions",
				Columns:    []*schema.Column{SkillVersionsColumns[7]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skillversion_skill_id_version",
				Unique:  true,
				Columns: []*schema.Column{SkillVersionsColumns[7], SkillVersionsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LocalizedDescriptionsTable,
		RepositoriesTable,
		SkillRiskAssessmentsTable,
		SkillsTable,
		SkillVersionsTable,
	}
)

func init() {
	SkillRiskAssessmentsTable.ForeignKeys[0].RefTable = SkillVersionsTable
	SkillRiskAssessmentsTable.Annotation = &entsql.Annotation{
		Table: "skill_risk_assessments",
	}
	SkillsTable.ForeignKeys[0].RefTable = RepositoriesTable
	SkillVersionsTable.ForeignKeys[0].RefTable = SkillsTable
}
