/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangLlmsFullDottxtRouteImport } from './routes/$lang/llms-full[.]txt'
import { Route as LangLlmsDottxtRouteImport } from './routes/$lang/llms[.]txt'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'
import { Route as LangDocsChar123Char125DotmdRouteImport } from './routes/$lang/docs/{$}[.]md'
import { Route as LangHubIndexRouteImport } from './routes/$lang/hub/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangLlmsFullDottxtRoute = LangLlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => LangRoute,
} as any)
const LangLlmsDottxtRoute = LangLlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => LangRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsChar123Char125DotmdRoute =
  LangDocsChar123Char125DotmdRouteImport.update({
    id: '/docs/{$}.md',
    path: '/docs/{$}.md',
    getParentRoute: () => LangRoute,
  } as any)
const LangHubIndexRoute = LangHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/hub': typeof HubRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/hub/': typeof LangHubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub': typeof HubRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/hub': typeof LangHubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/hub': typeof HubRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/hub/': typeof LangHubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/hub'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/hub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hub'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/$lang'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/hub'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/hub'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  HubRoute: typeof HubRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/llms-full.txt': {
      id: '/$lang/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/$lang/llms-full.txt'
      preLoaderRoute: typeof LangLlmsFullDottxtRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/llms.txt': {
      id: '/$lang/llms.txt'
      path: '/llms.txt'
      fullPath: '/$lang/llms.txt'
      preLoaderRoute: typeof LangLlmsDottxtRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs/{$}.md': {
      id: '/$lang/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/$lang/docs/{$}.md'
      preLoaderRoute: typeof LangDocsChar123Char125DotmdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/hub/': {
      id: '/$lang/hub/'
      path: '/hub'
      fullPath: '/$lang/hub/'
      preLoaderRoute: typeof LangHubIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangLlmsFullDottxtRoute: typeof LangLlmsFullDottxtRoute
  LangLlmsDottxtRoute: typeof LangLlmsDottxtRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangDocsChar123Char125DotmdRoute: typeof LangDocsChar123Char125DotmdRoute
  LangHubIndexRoute: typeof LangHubIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLlmsFullDottxtRoute: LangLlmsFullDottxtRoute,
  LangLlmsDottxtRoute: LangLlmsDottxtRoute,
  LangIndexRoute: LangIndexRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangDocsChar123Char125DotmdRoute: LangDocsChar123Char125DotmdRoute,
  LangHubIndexRoute: LangHubIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  HubRoute: HubRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
