// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/localizeddescription"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repository"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/riskassessment"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillversion"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// LocalizedDescription is the client for interacting with the LocalizedDescription builders.
	LocalizedDescription *LocalizedDescriptionClient
	// Repository is the client for interacting with the Repository builders.
	Repository *RepositoryClient
	// RiskAssessment is the client for interacting with the RiskAssessment builders.
	RiskAssessment *RiskAssessmentClient
	// Skill is the client for interacting with the Skill builders.
	Skill *SkillClient
	// SkillVersion is the client for interacting with the SkillVersion builders.
	SkillVersion *SkillVersionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.LocalizedDescription = NewLocalizedDescriptionClient(c.config)
	c.Repository = NewRepositoryClient(c.config)
	c.RiskAssessment = NewRiskAssessmentClient(c.config)
	c.Skill = NewSkillClient(c.config)
	c.SkillVersion = NewSkillVersionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		LocalizedDescription: NewLocalizedDescriptionClient(cfg),
		Repository:           NewRepositoryClient(cfg),
		RiskAssessment:       NewRiskAssessmentClient(cfg),
		Skill:                NewSkillClient(cfg),
		SkillVersion:         NewSkillVersionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		LocalizedDescription: NewLocalizedDescriptionClient(cfg),
		Repository:           NewRepositoryClient(cfg),
		RiskAssessment:       NewRiskAssessmentClient(cfg),
		Skill:                NewSkillClient(cfg),
		SkillVersion:         NewSkillVersionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		LocalizedDescription.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.LocalizedDescription.Use(hooks...)
	c.Repository.Use(hooks...)
	c.RiskAssessment.Use(hooks...)
	c.Skill.Use(hooks...)
	c.SkillVersion.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.LocalizedDescription.Intercept(interceptors...)
	c.Repository.Intercept(interceptors...)
	c.RiskAssessment.Intercept(interceptors...)
	c.Skill.Intercept(interceptors...)
	c.SkillVersion.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *LocalizedDescriptionMutation:
		return c.LocalizedDescription.mutate(ctx, m)
	case *RepositoryMutation:
		return c.Repository.mutate(ctx, m)
	case *RiskAssessmentMutation:
		return c.RiskAssessment.mutate(ctx, m)
	case *SkillMutation:
		return c.Skill.mutate(ctx, m)
	case *SkillVersionMutation:
		return c.SkillVersion.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// LocalizedDescriptionClient is a client for the LocalizedDescription schema.
type LocalizedDescriptionClient struct {
	config
}

// NewLocalizedDescriptionClient returns a client for the LocalizedDescription from the given config.
func NewLocalizedDescriptionClient(c config) *LocalizedDescriptionClient {
	return &LocalizedDescriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `localizeddescription.Hooks(f(g(h())))`.
func (c *LocalizedDescriptionClient) Use(hooks ...Hook) {
	c.hooks.LocalizedDescription = append(c.hooks.LocalizedDescription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `localizeddescription.Intercept(f(g(h())))`.
func (c *LocalizedDescriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.LocalizedDescription = append(c.inters.LocalizedDescription, interceptors...)
}

// Create returns a builder for creating a LocalizedDescription entity.
func (c *LocalizedDescriptionClient) Create() *LocalizedDescriptionCreate {
	mutation := newLocalizedDescriptionMutation(c.config, OpCreate)
	return &LocalizedDescriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LocalizedDescription entities.
func (c *LocalizedDescriptionClient) CreateBulk(builders ...*LocalizedDescriptionCreate) *LocalizedDescriptionCreateBulk {
	return &LocalizedDescriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LocalizedDescriptionClient) MapCreateBulk(slice any, setFunc func(*LocalizedDescriptionCreate, int)) *LocalizedDescriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LocalizedDescriptionCreateBulk{err: fmt.Errorf("calling to LocalizedDescriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LocalizedDescriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LocalizedDescriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LocalizedDescription.
func (c *LocalizedDescriptionClient) Update() *LocalizedDescriptionUpdate {
	mutation := newLocalizedDescriptionMutation(c.config, OpUpdate)
	return &LocalizedDescriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LocalizedDescriptionClient) UpdateOne(_m *LocalizedDescription) *LocalizedDescriptionUpdateOne {
	mutation := newLocalizedDescriptionMutation(c.config, OpUpdateOne, withLocalizedDescription(_m))
	return &LocalizedDescriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LocalizedDescriptionClient) UpdateOneID(id int64) *LocalizedDescriptionUpdateOne {
	mutation := newLocalizedDescriptionMutation(c.config, OpUpdateOne, withLocalizedDescriptionID(id))
	return &LocalizedDescriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LocalizedDescription.
func (c *LocalizedDescriptionClient) Delete() *LocalizedDescriptionDelete {
	mutation := newLocalizedDescriptionMutation(c.config, OpDelete)
	return &LocalizedDescriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LocalizedDescriptionClient) DeleteOne(_m *LocalizedDescription) *LocalizedDescriptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LocalizedDescriptionClient) DeleteOneID(id int64) *LocalizedDescriptionDeleteOne {
	builder := c.Delete().Where(localizeddescription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LocalizedDescriptionDeleteOne{builder}
}

// Query returns a query builder for LocalizedDescription.
func (c *LocalizedDescriptionClient) Query() *LocalizedDescriptionQuery {
	return &LocalizedDescriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLocalizedDescription},
		inters: c.Interceptors(),
	}
}

// Get returns a LocalizedDescription entity by its id.
func (c *LocalizedDescriptionClient) Get(ctx context.Context, id int64) (*LocalizedDescription, error) {
	return c.Query().Where(localizeddescription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LocalizedDescriptionClient) GetX(ctx context.Context, id int64) *LocalizedDescription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LocalizedDescriptionClient) Hooks() []Hook {
	return c.hooks.LocalizedDescription
}

// Interceptors returns the client interceptors.
func (c *LocalizedDescriptionClient) Interceptors() []Interceptor {
	return c.inters.LocalizedDescription
}

func (c *LocalizedDescriptionClient) mutate(ctx context.Context, m *LocalizedDescriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LocalizedDescriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LocalizedDescriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LocalizedDescriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LocalizedDescriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LocalizedDescription mutation op: %q", m.Op())
	}
}

// RepositoryClient is a client for the Repository schema.
type RepositoryClient struct {
	config
}

// NewRepositoryClient returns a client for the Repository from the given config.
func NewRepositoryClient(c config) *RepositoryClient {
	return &RepositoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repository.Hooks(f(g(h())))`.
func (c *RepositoryClient) Use(hooks ...Hook) {
	c.hooks.Repository = append(c.hooks.Repository, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `repository.Intercept(f(g(h())))`.
func (c *RepositoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Repository = append(c.inters.Repository, interceptors...)
}

// Create returns a builder for creating a Repository entity.
func (c *RepositoryClient) Create() *RepositoryCreate {
	mutation := newRepositoryMutation(c.config, OpCreate)
	return &RepositoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Repository entities.
func (c *RepositoryClient) CreateBulk(builders ...*RepositoryCreate) *RepositoryCreateBulk {
	return &RepositoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RepositoryClient) MapCreateBulk(slice any, setFunc func(*RepositoryCreate, int)) *RepositoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RepositoryCreateBulk{err: fmt.Errorf("calling to RepositoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RepositoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RepositoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Repository.
func (c *RepositoryClient) Update() *RepositoryUpdate {
	mutation := newRepositoryMutation(c.config, OpUpdate)
	return &RepositoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepositoryClient) UpdateOne(_m *Repository) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepository(_m))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepositoryClient) UpdateOneID(id int64) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepositoryID(id))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repository.
func (c *RepositoryClient) Delete() *RepositoryDelete {
	mutation := newRepositoryMutation(c.config, OpDelete)
	return &RepositoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RepositoryClient) DeleteOne(_m *Repository) *RepositoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RepositoryClient) DeleteOneID(id int64) *RepositoryDeleteOne {
	builder := c.Delete().Where(repository.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepositoryDeleteOne{builder}
}

// Query returns a query builder for Repository.
func (c *RepositoryClient) Query() *RepositoryQuery {
	return &RepositoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRepository},
		inters: c.Interceptors(),
	}
}

// Get returns a Repository entity by its id.
func (c *RepositoryClient) Get(ctx context.Context, id int64) (*Repository, error) {
	return c.Query().Where(repository.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepositoryClient) GetX(ctx context.Context, id int64) *Repository {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySkills queries the skills edge of a Repository.
func (c *RepositoryClient) QuerySkills(_m *Repository) *SkillQuery {
	query := (&SkillClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, id),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.SkillsTable, repository.SkillsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepositoryClient) Hooks() []Hook {
	return c.hooks.Repository
}

// Interceptors returns the client interceptors.
func (c *RepositoryClient) Interceptors() []Interceptor {
	return c.inters.Repository
}

func (c *RepositoryClient) mutate(ctx context.Context, m *RepositoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RepositoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RepositoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RepositoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Repository mutation op: %q", m.Op())
	}
}

// RiskAssessmentClient is a client for the RiskAssessment schema.
type RiskAssessmentClient struct {
	config
}

// NewRiskAssessmentClient returns a client for the RiskAssessment from the given config.
func NewRiskAssessmentClient(c config) *RiskAssessmentClient {
	return &RiskAssessmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `riskassessment.Hooks(f(g(h())))`.
func (c *RiskAssessmentClient) Use(hooks ...Hook) {
	c.hooks.RiskAssessment = append(c.hooks.RiskAssessment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `riskassessment.Intercept(f(g(h())))`.
func (c *RiskAssessmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.RiskAssessment = append(c.inters.RiskAssessment, interceptors...)
}

// Create returns a builder for creating a RiskAssessment entity.
func (c *RiskAssessmentClient) Create() *RiskAssessmentCreate {
	mutation := newRiskAssessmentMutation(c.config, OpCreate)
	return &RiskAssessmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RiskAssessment entities.
func (c *RiskAssessmentClient) CreateBulk(builders ...*RiskAssessmentCreate) *RiskAssessmentCreateBulk {
	return &RiskAssessmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RiskAssessmentClient) MapCreateBulk(slice any, setFunc func(*RiskAssessmentCreate, int)) *RiskAssessmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RiskAssessmentCreateBulk{err: fmt.Errorf("calling to RiskAssessmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RiskAssessmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RiskAssessmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RiskAssessment.
func (c *RiskAssessmentClient) Update() *RiskAssessmentUpdate {
	mutation := newRiskAssessmentMutation(c.config, OpUpdate)
	return &RiskAssessmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RiskAssessmentClient) UpdateOne(_m *RiskAssessment) *RiskAssessmentUpdateOne {
	mutation := newRiskAssessmentMutation(c.config, OpUpdateOne, withRiskAssessment(_m))
	return &RiskAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RiskAssessmentClient) UpdateOneID(id int64) *RiskAssessmentUpdateOne {
	mutation := newRiskAssessmentMutation(c.config, OpUpdateOne, withRiskAssessmentID(id))
	return &RiskAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RiskAssessment.
func (c *RiskAssessmentClient) Delete() *RiskAssessmentDelete {
	mutation := newRiskAssessmentMutation(c.config, OpDelete)
	return &RiskAssessmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RiskAssessmentClient) DeleteOne(_m *RiskAssessment) *RiskAssessmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RiskAssessmentClient) DeleteOneID(id int64) *RiskAssessmentDeleteOne {
	builder := c.Delete().Where(riskassessment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RiskAssessmentDeleteOne{builder}
}

// Query returns a query builder for RiskAssessment.
func (c *RiskAssessmentClient) Query() *RiskAssessmentQuery {
	return &RiskAssessmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRiskAssessment},
		inters: c.Interceptors(),
	}
}

// Get returns a RiskAssessment entity by its id.
func (c *RiskAssessmentClient) Get(ctx context.Context, id int64) (*RiskAssessment, error) {
	return c.Query().Where(riskassessment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RiskAssessmentClient) GetX(ctx context.Context, id int64) *RiskAssessment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySkillVersion queries the skill_version edge of a RiskAssessment.
func (c *RiskAssessmentClient) QuerySkillVersion(_m *RiskAssessment) *SkillVersionQuery {
	query := (&SkillVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(riskassessment.Table, riskassessment.FieldID, id),
			sqlgraph.To(skillversion.Table, skillversion.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, riskassessment.SkillVersionTable, riskassessment.SkillVersionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RiskAssessmentClient) Hooks() []Hook {
	return c.hooks.RiskAssessment
}

// Interceptors returns the client interceptors.
func (c *RiskAssessmentClient) Interceptors() []Interceptor {
	return c.inters.RiskAssessment
}

func (c *RiskAssessmentClient) mutate(ctx context.Context, m *RiskAssessmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RiskAssessmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RiskAssessmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RiskAssessmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RiskAssessmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RiskAssessment mutation op: %q", m.Op())
	}
}

// SkillClient is a client for the Skill schema.
type SkillClient struct {
	config
}

// NewSkillClient returns a client for the Skill from the given config.
func NewSkillClient(c config) *SkillClient {
	return &SkillClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `skill.Hooks(f(g(h())))`.
func (c *SkillClient) Use(hooks ...Hook) {
	c.hooks.Skill = append(c.hooks.Skill, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `skill.Intercept(f(g(h())))`.
func (c *SkillClient) Intercept(interceptors ...Interceptor) {
	c.inters.Skill = append(c.inters.Skill, interceptors...)
}

// Create returns a builder for creating a Skill entity.
func (c *SkillClient) Create() *SkillCreate {
	mutation := newSkillMutation(c.config, OpCreate)
	return &SkillCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Skill entities.
func (c *SkillClient) CreateBulk(builders ...*SkillCreate) *SkillCreateBulk {
	return &SkillCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SkillClient) MapCreateBulk(slice any, setFunc func(*SkillCreate, int)) *SkillCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SkillCreateBulk{err: fmt.Errorf("calling to SkillClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SkillCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SkillCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Skill.
func (c *SkillClient) Update() *SkillUpdate {
	mutation := newSkillMutation(c.config, OpUpdate)
	return &SkillUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SkillClient) UpdateOne(_m *Skill) *SkillUpdateOne {
	mutation := newSkillMutation(c.config, OpUpdateOne, withSkill(_m))
	return &SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SkillClient) UpdateOneID(id int64) *SkillUpdateOne {
	mutation := newSkillMutation(c.config, OpUpdateOne, withSkillID(id))
	return &SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Skill.
func (c *SkillClient) Delete() *SkillDelete {
	mutation := newSkillMutation(c.config, OpDelete)
	return &SkillDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SkillClient) DeleteOne(_m *Skill) *SkillDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SkillClient) DeleteOneID(id int64) *SkillDeleteOne {
	builder := c.Delete().Where(skill.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SkillDeleteOne{builder}
}

// Query returns a query builder for Skill.
func (c *SkillClient) Query() *SkillQuery {
	return &SkillQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSkill},
		inters: c.Interceptors(),
	}
}

// Get returns a Skill entity by its id.
func (c *SkillClient) Get(ctx context.Context, id int64) (*Skill, error) {
	return c.Query().Where(skill.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SkillClient) GetX(ctx context.Context, id int64) *Skill {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySourceRepository queries the source_repository edge of a Skill.
func (c *SkillClient) QuerySourceRepository(_m *Skill) *RepositoryQuery {
	query := (&RepositoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skill.Table, skill.FieldID, id),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, skill.SourceRepositoryTable, skill.SourceRepositoryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryVersions queries the versions edge of a Skill.
func (c *SkillClient) QueryVersions(_m *Skill) *SkillVersionQuery {
	query := (&SkillVersionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skill.Table, skill.FieldID, id),
			sqlgraph.To(skillversion.Table, skillversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, skill.VersionsTable, skill.VersionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SkillClient) Hooks() []Hook {
	return c.hooks.Skill
}

// Interceptors returns the client interceptors.
func (c *SkillClient) Interceptors() []Interceptor {
	return c.inters.Skill
}

func (c *SkillClient) mutate(ctx context.Context, m *SkillMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SkillCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SkillUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SkillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SkillDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Skill mutation op: %q", m.Op())
	}
}

// SkillVersionClient is a client for the SkillVersion schema.
type SkillVersionClient struct {
	config
}

// NewSkillVersionClient returns a client for the SkillVersion from the given config.
func NewSkillVersionClient(c config) *SkillVersionClient {
	return &SkillVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `skillversion.Hooks(f(g(h())))`.
func (c *SkillVersionClient) Use(hooks ...Hook) {
	c.hooks.SkillVersion = append(c.hooks.SkillVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `skillversion.Intercept(f(g(h())))`.
func (c *SkillVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.SkillVersion = append(c.inters.SkillVersion, interceptors...)
}

// Create returns a builder for creating a SkillVersion entity.
func (c *SkillVersionClient) Create() *SkillVersionCreate {
	mutation := newSkillVersionMutation(c.config, OpCreate)
	return &SkillVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SkillVersion entities.
func (c *SkillVersionClient) CreateBulk(builders ...*SkillVersionCreate) *SkillVersionCreateBulk {
	return &SkillVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SkillVersionClient) MapCreateBulk(slice any, setFunc func(*SkillVersionCreate, int)) *SkillVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SkillVersionCreateBulk{err: fmt.Errorf("calling to SkillVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SkillVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SkillVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SkillVersion.
func (c *SkillVersionClient) Update() *SkillVersionUpdate {
	mutation := newSkillVersionMutation(c.config, OpUpdate)
	return &SkillVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SkillVersionClient) UpdateOne(_m *SkillVersion) *SkillVersionUpdateOne {
	mutation := newSkillVersionMutation(c.config, OpUpdateOne, withSkillVersion(_m))
	return &SkillVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SkillVersionClient) UpdateOneID(id int64) *SkillVersionUpdateOne {
	mutation := newSkillVersionMutation(c.config, OpUpdateOne, withSkillVersionID(id))
	return &SkillVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SkillVersion.
func (c *SkillVersionClient) Delete() *SkillVersionDelete {
	mutation := newSkillVersionMutation(c.config, OpDelete)
	return &SkillVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SkillVersionClient) DeleteOne(_m *SkillVersion) *SkillVersionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SkillVersionClient) DeleteOneID(id int64) *SkillVersionDeleteOne {
	builder := c.Delete().Where(skillversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SkillVersionDeleteOne{builder}
}

// Query returns a query builder for SkillVersion.
func (c *SkillVersionClient) Query() *SkillVersionQuery {
	return &SkillVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSkillVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a SkillVersion entity by its id.
func (c *SkillVersionClient) Get(ctx context.Context, id int64) (*SkillVersion, error) {
	return c.Query().Where(skillversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SkillVersionClient) GetX(ctx context.Context, id int64) *SkillVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySkill queries the skill edge of a SkillVersion.
func (c *SkillVersionClient) QuerySkill(_m *SkillVersion) *SkillQuery {
	query := (&SkillClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skillversion.Table, skillversion.FieldID, id),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, skillversion.SkillTable, skillversion.SkillColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRiskAssessments queries the risk_assessments edge of a SkillVersion.
func (c *SkillVersionClient) QueryRiskAssessments(_m *SkillVersion) *RiskAssessmentQuery {
	query := (&RiskAssessmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(skillversion.Table, skillversion.FieldID, id),
			sqlgraph.To(riskassessment.Table, riskassessment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, skillversion.RiskAssessmentsTable, skillversion.RiskAssessmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SkillVersionClient) Hooks() []Hook {
	return c.hooks.SkillVersion
}

// Interceptors returns the client interceptors.
func (c *SkillVersionClient) Interceptors() []Interceptor {
	return c.inters.SkillVersion
}

func (c *SkillVersionClient) mutate(ctx context.Context, m *SkillVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SkillVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SkillVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SkillVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SkillVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SkillVersion mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		LocalizedDescription, Repository, RiskAssessment, Skill, SkillVersion []ent.Hook
	}
	inters struct {
		LocalizedDescription, Repository, RiskAssessment, Skill,
		SkillVersion []ent.Interceptor
	}
)
