// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/installevent"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
)

// InstallEvent is the model entity for the InstallEvent schema.
type InstallEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID int64 `json:"skill_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Agents holds the value of the "agents" field.
	Agents string `json:"agents,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// CliVersion holds the value of the "cli_version" field.
	CliVersion string `json:"cli_version,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InstallEventQuery when eager-loading is set.
	Edges        InstallEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InstallEventEdges holds the relations/edges for other nodes in the graph.
type InstallEventEdges struct {
	// Skill holds the value of the skill edge.
	Skill *Skill `json:"skill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InstallEventEdges) SkillOrErr() (*Skill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InstallEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case installevent.FieldSkillID:
			values[i] = new(sql.NullInt64)
		case installevent.FieldID, installevent.FieldVersion, installevent.FieldAgents, installevent.FieldScope, installevent.FieldCliVersion:
			values[i] = new(sql.NullString)
		case installevent.FieldOccurredAt, installevent.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InstallEvent fields.
func (_m *InstallEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case installevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case installevent.FieldSkillID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.Int64
			}
		case installevent.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case installevent.FieldAgents:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agents", values[i])
			} else if value.Valid {
				_m.Agents = value.String
			}
		case installevent.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case installevent.FieldCliVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cli_version", values[i])
			} else if value.Valid {
				_m.CliVersion = value.String
			}
		case installevent.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case installevent.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InstallEvent.
// This includes values selected through modifiers, order, etc.
func (_m *InstallEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySkill queries the "skill" edge of the InstallEvent entity.
func (_m *InstallEvent) QuerySkill() *SkillQuery {
	return NewInstallEventClient(_m.config).QuerySkill(_m)
}

// Update returns a builder for updating this InstallEvent.
// Note that you need to call InstallEvent.Unwrap() before calling this method if this InstallEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InstallEvent) Update() *InstallEventUpdateOne {
	return NewInstallEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InstallEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InstallEvent) Unwrap() *InstallEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InstallEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InstallEvent) String() string {
	var builder strings.Builder
	builder.WriteString("InstallEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("agents=")
	builder.WriteString(_m.Agents)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("cli_version=")
	builder.WriteString(_m.CliVersion)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InstallEvents is a parsable slice of InstallEvent.
type InstallEvents []*InstallEvent
