// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/installevent"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
)

// InstallEventUpdate is the builder for updating InstallEvent entities.
type InstallEventUpdate struct {
	config
	hooks    []Hook
	mutation *InstallEventMutation
}

// Where appends a list predicates to the InstallEventUpdate builder.
func (_u *InstallEventUpdate) Where(ps ...predicate.InstallEvent) *InstallEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *InstallEventUpdate) SetSkillID(v int64) *InstallEventUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableSkillID(v *int64) *InstallEventUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *InstallEventUpdate) SetVersion(v string) *InstallEventUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableVersion(v *string) *InstallEventUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetAgents sets the "agents" field.
func (_u *InstallEventUpdate) SetAgents(v string) *InstallEventUpdate {
	_u.mutation.SetAgents(v)
	return _u
}

// SetNillableAgents sets the "agents" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableAgents(v *string) *InstallEventUpdate {
	if v != nil {
		_u.SetAgents(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *InstallEventUpdate) SetScope(v string) *InstallEventUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableScope(v *string) *InstallEventUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetCliVersion sets the "cli_version" field.
func (_u *InstallEventUpdate) SetCliVersion(v string) *InstallEventUpdate {
	_u.mutation.SetCliVersion(v)
	return _u
}

// SetNillableCliVersion sets the "cli_version" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableCliVersion(v *string) *InstallEventUpdate {
	if v != nil {
		_u.SetCliVersion(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *InstallEventUpdate) SetOccurredAt(v time.Time) *InstallEventUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableOccurredAt(v *time.Time) *InstallEventUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *InstallEventUpdate) SetReceivedAt(v time.Time) *InstallEventUpdate {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *InstallEventUpdate) SetNillableReceivedAt(v *time.Time) *InstallEventUpdate {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *InstallEventUpdate) SetSkill(v *Skill) *InstallEventUpdate {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the InstallEventMutation object of the builder.
func (_u *InstallEventUpdate) Mutation() *InstallEventMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *InstallEventUpdate) ClearSkill() *InstallEventUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstallEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstallEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstallEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstallEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstallEventUpdate) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InstallEvent.skill"`)
	}
	return nil
}

func (_u *InstallEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(installevent.Table, installevent.Columns, sqlgraph.NewFieldSpec(installevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(installevent.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Agents(); ok {
		_spec.SetField(installevent.FieldAgents, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(installevent.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CliVersion(); ok {
		_spec.SetField(installevent.FieldCliVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(installevent.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(installevent.FieldReceivedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   installevent.SkillTable,
			Columns: []string{installevent.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   installevent.SkillTable,
			Columns: []string{installevent.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{installevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstallEventUpdateOne is the builder for updating a single InstallEvent entity.
type InstallEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstallEventMutation
}

// SetSkillID sets the "skill_id" field.
func (_u *InstallEventUpdateOne) SetSkillID(v int64) *InstallEventUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableSkillID(v *int64) *InstallEventUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *InstallEventUpdateOne) SetVersion(v string) *InstallEventUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableVersion(v *string) *InstallEventUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetAgents sets the "agents" field.
func (_u *InstallEventUpdateOne) SetAgents(v string) *InstallEventUpdateOne {
	_u.mutation.SetAgents(v)
	return _u
}

// SetNillableAgents sets the "agents" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableAgents(v *string) *InstallEventUpdateOne {
	if v != nil {
		_u.SetAgents(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *InstallEventUpdateOne) SetScope(v string) *InstallEventUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableScope(v *string) *InstallEventUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetCliVersion sets the "cli_version" field.
func (_u *InstallEventUpdateOne) SetCliVersion(v string) *InstallEventUpdateOne {
	_u.mutation.SetCliVersion(v)
	return _u
}

// SetNillableCliVersion sets the "cli_version" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableCliVersion(v *string) *InstallEventUpdateOne {
	if v != nil {
		_u.SetCliVersion(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *InstallEventUpdateOne) SetOccurredAt(v time.Time) *InstallEventUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableOccurredAt(v *time.Time) *InstallEventUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *InstallEventUpdateOne) SetReceivedAt(v time.Time) *InstallEventUpdateOne {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *InstallEventUpdateOne) SetNillableReceivedAt(v *time.Time) *InstallEventUpdateOne {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *InstallEventUpdateOne) SetSkill(v *Skill) *InstallEventUpdateOne {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the InstallEventMutation object of the builder.
func (_u *InstallEventUpdateOne) Mutation() *InstallEventMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *InstallEventUpdateOne) ClearSkill() *InstallEventUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// Where appends a list predicates to the InstallEventUpdate builder.
func (_u *InstallEventUpdateOne) Where(ps ...predicate.InstallEvent) *InstallEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstallEventUpdateOne) Select(field string, fields ...string) *InstallEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InstallEvent entity.
func (_u *InstallEventUpdateOne) Save(ctx context.Context) (*InstallEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstallEventUpdateOne) SaveX(ctx context.Context) *InstallEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstallEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstallEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstallEventUpdateOne) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InstallEvent.skill"`)
	}
	return nil
}

func (_u *InstallEventUpdateOne) sqlSave(ctx context.Context) (_node *InstallEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(installevent.Table, installevent.Columns, sqlgraph.NewFieldSpec(installevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InstallEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, installevent.FieldID)
		for _, f := range fields {
			if !installevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != installevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(installevent.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Agents(); ok {
		_spec.SetField(installevent.FieldAgents, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(installevent.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CliVersion(); ok {
		_spec.SetField(installevent.FieldCliVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(installevent.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(installevent.FieldReceivedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   installevent.SkillTable,
			Columns: []string{installevent.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   installevent.SkillTable,
			Columns: []string{installevent.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InstallEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{installevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
