// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/localizeddescription"
)

// LocalizedDescriptionCreate is the builder for creating a LocalizedDescription entity.
type LocalizedDescriptionCreate struct {
	config
	mutation *LocalizedDescriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResourceKind sets the "resource_kind" field.
func (_c *LocalizedDescriptionCreate) SetResourceKind(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetResourceKind(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *LocalizedDescriptionCreate) SetResourceID(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetLocale sets the "locale" field.
func (_c *LocalizedDescriptionCreate) SetLocale(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *LocalizedDescriptionCreate) SetDescription(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetSourceDigest sets the "source_digest" field.
func (_c *LocalizedDescriptionCreate) SetSourceDigest(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetSourceDigest(v)
	return _c
}

// SetPromptVersion sets the "prompt_version" field.
func (_c *LocalizedDescriptionCreate) SetPromptVersion(v string) *LocalizedDescriptionCreate {
	_c.mutation.SetPromptVersion(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LocalizedDescriptionCreate) SetCreatedAt(v time.Time) *LocalizedDescriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LocalizedDescriptionCreate) SetNillableCreatedAt(v *time.Time) *LocalizedDescriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LocalizedDescriptionCreate) SetUpdatedAt(v time.Time) *LocalizedDescriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LocalizedDescriptionCreate) SetNillableUpdatedAt(v *time.Time) *LocalizedDescriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LocalizedDescriptionCreate) SetID(v int64) *LocalizedDescriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LocalizedDescriptionMutation object of the builder.
func (_c *LocalizedDescriptionCreate) Mutation() *LocalizedDescriptionMutation {
	return _c.mutation
}

// Save creates the LocalizedDescription in the database.
func (_c *LocalizedDescriptionCreate) Save(ctx context.Context) (*LocalizedDescription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocalizedDescriptionCreate) SaveX(ctx context.Context) *LocalizedDescription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocalizedDescriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocalizedDescriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LocalizedDescriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := localizeddescription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := localizeddescription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocalizedDescriptionCreate) check() error {
	if _, ok := _c.mutation.ResourceKind(); !ok {
		return &ValidationError{Name: "resource_kind", err: errors.New(`ent: missing required field "LocalizedDescription.resource_kind"`)}
	}
	if v, ok := _c.mutation.ResourceKind(); ok {
		if err := localizeddescription.ResourceKindValidator(v); err != nil {
			return &ValidationError{Name: "resource_kind", err: fmt.Errorf(`ent: validator failed for field "LocalizedDescription.resource_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "LocalizedDescription.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := localizeddescription.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "LocalizedDescription.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "locale", err: errors.New(`ent: missing required field "LocalizedDescription.locale"`)}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := localizeddescription.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "LocalizedDescription.locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "LocalizedDescription.description"`)}
	}
	if _, ok := _c.mutation.SourceDigest(); !ok {
		return &ValidationError{Name: "source_digest", err: errors.New(`ent: missing required field "LocalizedDescription.source_digest"`)}
	}
	if v, ok := _c.mutation.SourceDigest(); ok {
		if err := localizeddescription.SourceDigestValidator(v); err != nil {
			return &ValidationError{Name: "source_digest", err: fmt.Errorf(`ent: validator failed for field "LocalizedDescription.source_digest": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromptVersion(); !ok {
		return &ValidationError{Name: "prompt_version", err: errors.New(`ent: missing required field "LocalizedDescription.prompt_version"`)}
	}
	if v, ok := _c.mutation.PromptVersion(); ok {
		if err := localizeddescription.PromptVersionValidator(v); err != nil {
			return &ValidationError{Name: "prompt_version", err: fmt.Errorf(`ent: validator failed for field "LocalizedDescription.prompt_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LocalizedDescription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LocalizedDescription.updated_at"`)}
	}
	return nil
}

func (_c *LocalizedDescriptionCreate) sqlSave(ctx context.Context) (*LocalizedDescription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocalizedDescriptionCreate) createSpec() (*LocalizedDescription, *sqlgraph.CreateSpec) {
	var (
		_node = &LocalizedDescription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(localizeddescription.Table, sqlgraph.NewFieldSpec(localizeddescription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ResourceKind(); ok {
		_spec.SetField(localizeddescription.FieldResourceKind, field.TypeString, value)
		_node.ResourceKind = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(localizeddescription.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(localizeddescription.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(localizeddescription.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SourceDigest(); ok {
		_spec.SetField(localizeddescription.FieldSourceDigest, field.TypeString, value)
		_node.SourceDigest = value
	}
	if value, ok := _c.mutation.PromptVersion(); ok {
		_spec.SetField(localizeddescription.FieldPromptVersion, field.TypeString, value)
		_node.PromptVersion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(localizeddescription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(localizeddescription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LocalizedDescription.Create().
//		SetResourceKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LocalizedDescriptionUpsert) {
//			SetResourceKind(v+v).
//		}).
//		Exec(ctx)
func (_c *LocalizedDescriptionCreate) OnConflict(opts ...sql.ConflictOption) *LocalizedDescriptionUpsertOne {
	_c.conflict = opts
	return &LocalizedDescriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LocalizedDescriptionCreate) OnConflictColumns(columns ...string) *LocalizedDescriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LocalizedDescriptionUpsertOne{
		create: _c,
	}
}

type (
	// LocalizedDescriptionUpsertOne is the builder for "upsert"-ing
	//  one LocalizedDescription node.
	LocalizedDescriptionUpsertOne struct {
		create *LocalizedDescriptionCreate
	}

	// LocalizedDescriptionUpsert is the "OnConflict" setter.
	LocalizedDescriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetResourceKind sets the "resource_kind" field.
func (u *LocalizedDescriptionUpsert) SetResourceKind(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldResourceKind, v)
	return u
}

// UpdateResourceKind sets the "resource_kind" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateResourceKind() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldResourceKind)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *LocalizedDescriptionUpsert) SetResourceID(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateResourceID() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldResourceID)
	return u
}

// SetLocale sets the "locale" field.
func (u *LocalizedDescriptionUpsert) SetLocale(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldLocale, v)
	return u
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateLocale() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldLocale)
	return u
}

// SetDescription sets the "description" field.
func (u *LocalizedDescriptionUpsert) SetDescription(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateDescription() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldDescription)
	return u
}

// SetSourceDigest sets the "source_digest" field.
func (u *LocalizedDescriptionUpsert) SetSourceDigest(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldSourceDigest, v)
	return u
}

// UpdateSourceDigest sets the "source_digest" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateSourceDigest() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldSourceDigest)
	return u
}

// SetPromptVersion sets the "prompt_version" field.
func (u *LocalizedDescriptionUpsert) SetPromptVersion(v string) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldPromptVersion, v)
	return u
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdatePromptVersion() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldPromptVersion)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LocalizedDescriptionUpsert) SetCreatedAt(v time.Time) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateCreatedAt() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LocalizedDescriptionUpsert) SetUpdatedAt(v time.Time) *LocalizedDescriptionUpsert {
	u.Set(localizeddescription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsert) UpdateUpdatedAt() *LocalizedDescriptionUpsert {
	u.SetExcluded(localizeddescription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(localizeddescription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LocalizedDescriptionUpsertOne) UpdateNewValues() *LocalizedDescriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(localizeddescription.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LocalizedDescriptionUpsertOne) Ignore() *LocalizedDescriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LocalizedDescriptionUpsertOne) DoNothing() *LocalizedDescriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LocalizedDescriptionCreate.OnConflict
// documentation for more info.
func (u *LocalizedDescriptionUpsertOne) Update(set func(*LocalizedDescriptionUpsert)) *LocalizedDescriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LocalizedDescriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceKind sets the "resource_kind" field.
func (u *LocalizedDescriptionUpsertOne) SetResourceKind(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetResourceKind(v)
	})
}

// UpdateResourceKind sets the "resource_kind" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateResourceKind() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateResourceKind()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *LocalizedDescriptionUpsertOne) SetResourceID(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateResourceID() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateResourceID()
	})
}

// SetLocale sets the "locale" field.
func (u *LocalizedDescriptionUpsertOne) SetLocale(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateLocale() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateLocale()
	})
}

// SetDescription sets the "description" field.
func (u *LocalizedDescriptionUpsertOne) SetDescription(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateDescription() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateDescription()
	})
}

// SetSourceDigest sets the "source_digest" field.
func (u *LocalizedDescriptionUpsertOne) SetSourceDigest(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetSourceDigest(v)
	})
}

// UpdateSourceDigest sets the "source_digest" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateSourceDigest() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateSourceDigest()
	})
}

// SetPromptVersion sets the "prompt_version" field.
func (u *LocalizedDescriptionUpsertOne) SetPromptVersion(v string) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetPromptVersion(v)
	})
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdatePromptVersion() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdatePromptVersion()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LocalizedDescriptionUpsertOne) SetCreatedAt(v time.Time) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateCreatedAt() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LocalizedDescriptionUpsertOne) SetUpdatedAt(v time.Time) *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertOne) UpdateUpdatedAt() *LocalizedDescriptionUpsertOne {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LocalizedDescriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LocalizedDescriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LocalizedDescriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LocalizedDescriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LocalizedDescriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LocalizedDescriptionCreateBulk is the builder for creating many LocalizedDescription entities in bulk.
type LocalizedDescriptionCreateBulk struct {
	config
	err      error
	builders []*LocalizedDescriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the LocalizedDescription entities in the database.
func (_c *LocalizedDescriptionCreateBulk) Save(ctx context.Context) ([]*LocalizedDescription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LocalizedDescription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocalizedDescriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocalizedDescriptionCreateBulk) SaveX(ctx context.Context) []*LocalizedDescription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocalizedDescriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocalizedDescriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LocalizedDescription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LocalizedDescriptionUpsert) {
//			SetResourceKind(v+v).
//		}).
//		Exec(ctx)
func (_c *LocalizedDescriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *LocalizedDescriptionUpsertBulk {
	_c.conflict = opts
	return &LocalizedDescriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LocalizedDescriptionCreateBulk) OnConflictColumns(columns ...string) *LocalizedDescriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LocalizedDescriptionUpsertBulk{
		create: _c,
	}
}

// LocalizedDescriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of LocalizedDescription nodes.
type LocalizedDescriptionUpsertBulk struct {
	create *LocalizedDescriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(localizeddescription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LocalizedDescriptionUpsertBulk) UpdateNewValues() *LocalizedDescriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(localizeddescription.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LocalizedDescription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LocalizedDescriptionUpsertBulk) Ignore() *LocalizedDescriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LocalizedDescriptionUpsertBulk) DoNothing() *LocalizedDescriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LocalizedDescriptionCreateBulk.OnConflict
// documentation for more info.
func (u *LocalizedDescriptionUpsertBulk) Update(set func(*LocalizedDescriptionUpsert)) *LocalizedDescriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LocalizedDescriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceKind sets the "resource_kind" field.
func (u *LocalizedDescriptionUpsertBulk) SetResourceKind(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetResourceKind(v)
	})
}

// UpdateResourceKind sets the "resource_kind" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateResourceKind() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateResourceKind()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *LocalizedDescriptionUpsertBulk) SetResourceID(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateResourceID() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateResourceID()
	})
}

// SetLocale sets the "locale" field.
func (u *LocalizedDescriptionUpsertBulk) SetLocale(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateLocale() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateLocale()
	})
}

// SetDescription sets the "description" field.
func (u *LocalizedDescriptionUpsertBulk) SetDescription(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateDescription() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateDescription()
	})
}

// SetSourceDigest sets the "source_digest" field.
func (u *LocalizedDescriptionUpsertBulk) SetSourceDigest(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetSourceDigest(v)
	})
}

// UpdateSourceDigest sets the "source_digest" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateSourceDigest() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateSourceDigest()
	})
}

// SetPromptVersion sets the "prompt_version" field.
func (u *LocalizedDescriptionUpsertBulk) SetPromptVersion(v string) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetPromptVersion(v)
	})
}

// UpdatePromptVersion sets the "prompt_version" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdatePromptVersion() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdatePromptVersion()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LocalizedDescriptionUpsertBulk) SetCreatedAt(v time.Time) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateCreatedAt() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LocalizedDescriptionUpsertBulk) SetUpdatedAt(v time.Time) *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LocalizedDescriptionUpsertBulk) UpdateUpdatedAt() *LocalizedDescriptionUpsertBulk {
	return u.Update(func(s *LocalizedDescriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LocalizedDescriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LocalizedDescriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LocalizedDescriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LocalizedDescriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
