// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/localizeddescription"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
)

// LocalizedDescriptionDelete is the builder for deleting a LocalizedDescription entity.
type LocalizedDescriptionDelete struct {
	config
	hooks    []Hook
	mutation *LocalizedDescriptionMutation
}

// Where appends a list predicates to the LocalizedDescriptionDelete builder.
func (_d *LocalizedDescriptionDelete) Where(ps ...predicate.LocalizedDescription) *LocalizedDescriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LocalizedDescriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LocalizedDescriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LocalizedDescriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(localizeddescription.Table, sqlgraph.NewFieldSpec(localizeddescription.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LocalizedDescriptionDeleteOne is the builder for deleting a single LocalizedDescription entity.
type LocalizedDescriptionDeleteOne struct {
	_d *LocalizedDescriptionDelete
}

// Where appends a list predicates to the LocalizedDescriptionDelete builder.
func (_d *LocalizedDescriptionDeleteOne) Where(ps ...predicate.LocalizedDescription) *LocalizedDescriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LocalizedDescriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{localizeddescription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LocalizedDescriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
