// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repository"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
)

// RepositoryCreate is the builder for creating a Repository entity.
type RepositoryCreate struct {
	config
	mutation *RepositoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceHost sets the "source_host" field.
func (_c *RepositoryCreate) SetSourceHost(v string) *RepositoryCreate {
	_c.mutation.SetSourceHost(v)
	return _c
}

// SetRepositoryPath sets the "repository_path" field.
func (_c *RepositoryCreate) SetRepositoryPath(v string) *RepositoryCreate {
	_c.mutation.SetRepositoryPath(v)
	return _c
}

// SetRepositoryID sets the "repository_id" field.
func (_c *RepositoryCreate) SetRepositoryID(v string) *RepositoryCreate {
	_c.mutation.SetRepositoryID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RepositoryCreate) SetDescription(v string) *RepositoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDescription(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStars sets the "stars" field.
func (_c *RepositoryCreate) SetStars(v int64) *RepositoryCreate {
	_c.mutation.SetStars(v)
	return _c
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStars(v *int64) *RepositoryCreate {
	if v != nil {
		_c.SetStars(*v)
	}
	return _c
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (_c *RepositoryCreate) SetSourceMetadataEtag(v string) *RepositoryCreate {
	_c.mutation.SetSourceMetadataEtag(v)
	return _c
}

// SetNillableSourceMetadataEtag sets the "source_metadata_etag" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableSourceMetadataEtag(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetSourceMetadataEtag(*v)
	}
	return _c
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (_c *RepositoryCreate) SetSourceMetadataCheckedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetSourceMetadataCheckedAt(v)
	return _c
}

// SetNillableSourceMetadataCheckedAt sets the "source_metadata_checked_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableSourceMetadataCheckedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetSourceMetadataCheckedAt(*v)
	}
	return _c
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (_c *RepositoryCreate) SetSourceMetadataRetryAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetSourceMetadataRetryAt(v)
	return _c
}

// SetNillableSourceMetadataRetryAt sets the "source_metadata_retry_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableSourceMetadataRetryAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetSourceMetadataRetryAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepositoryCreate) SetCreatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableCreatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepositoryCreate) SetUpdatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableUpdatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepositoryCreate) SetID(v int64) *RepositoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (_c *RepositoryCreate) AddSkillIDs(ids ...int64) *RepositoryCreate {
	_c.mutation.AddSkillIDs(ids...)
	return _c
}

// AddSkills adds the "skills" edges to the Skill entity.
func (_c *RepositoryCreate) AddSkills(v ...*Skill) *RepositoryCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSkillIDs(ids...)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_c *RepositoryCreate) Mutation() *RepositoryMutation {
	return _c.mutation
}

// Save creates the Repository in the database.
func (_c *RepositoryCreate) Save(ctx context.Context) (*Repository, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryCreate) SaveX(ctx context.Context) *Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepositoryCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := repository.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Stars(); !ok {
		v := repository.DefaultStars
		_c.mutation.SetStars(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repository.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repository.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryCreate) check() error {
	if _, ok := _c.mutation.SourceHost(); !ok {
		return &ValidationError{Name: "source_host", err: errors.New(`ent: missing required field "Repository.source_host"`)}
	}
	if v, ok := _c.mutation.SourceHost(); ok {
		if err := repository.SourceHostValidator(v); err != nil {
			return &ValidationError{Name: "source_host", err: fmt.Errorf(`ent: validator failed for field "Repository.source_host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepositoryPath(); !ok {
		return &ValidationError{Name: "repository_path", err: errors.New(`ent: missing required field "Repository.repository_path"`)}
	}
	if v, ok := _c.mutation.RepositoryPath(); ok {
		if err := repository.RepositoryPathValidator(v); err != nil {
			return &ValidationError{Name: "repository_path", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepositoryID(); !ok {
		return &ValidationError{Name: "repository_id", err: errors.New(`ent: missing required field "Repository.repository_id"`)}
	}
	if v, ok := _c.mutation.RepositoryID(); ok {
		if err := repository.RepositoryIDValidator(v); err != nil {
			return &ValidationError{Name: "repository_id", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Repository.description"`)}
	}
	if _, ok := _c.mutation.Stars(); !ok {
		return &ValidationError{Name: "stars", err: errors.New(`ent: missing required field "Repository.stars"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Repository.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Repository.updated_at"`)}
	}
	return nil
}

func (_c *RepositoryCreate) sqlSave(ctx context.Context) (*Repository, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryCreate) createSpec() (*Repository, *sqlgraph.CreateSpec) {
	var (
		_node = &Repository{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repository.Table, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SourceHost(); ok {
		_spec.SetField(repository.FieldSourceHost, field.TypeString, value)
		_node.SourceHost = value
	}
	if value, ok := _c.mutation.RepositoryPath(); ok {
		_spec.SetField(repository.FieldRepositoryPath, field.TypeString, value)
		_node.RepositoryPath = value
	}
	if value, ok := _c.mutation.RepositoryID(); ok {
		_spec.SetField(repository.FieldRepositoryID, field.TypeString, value)
		_node.RepositoryID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Stars(); ok {
		_spec.SetField(repository.FieldStars, field.TypeInt64, value)
		_node.Stars = value
	}
	if value, ok := _c.mutation.SourceMetadataEtag(); ok {
		_spec.SetField(repository.FieldSourceMetadataEtag, field.TypeString, value)
		_node.SourceMetadataEtag = value
	}
	if value, ok := _c.mutation.SourceMetadataCheckedAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataCheckedAt, field.TypeTime, value)
		_node.SourceMetadataCheckedAt = &value
	}
	if value, ok := _c.mutation.SourceMetadataRetryAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataRetryAt, field.TypeTime, value)
		_node.SourceMetadataRetryAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Repository.Create().
//		SetSourceHost(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RepositoryUpsert) {
//			SetSourceHost(v+v).
//		}).
//		Exec(ctx)
func (_c *RepositoryCreate) OnConflict(opts ...sql.ConflictOption) *RepositoryUpsertOne {
	_c.conflict = opts
	return &RepositoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Repository.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RepositoryCreate) OnConflictColumns(columns ...string) *RepositoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RepositoryUpsertOne{
		create: _c,
	}
}

type (
	// RepositoryUpsertOne is the builder for "upsert"-ing
	//  one Repository node.
	RepositoryUpsertOne struct {
		create *RepositoryCreate
	}

	// RepositoryUpsert is the "OnConflict" setter.
	RepositoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceHost sets the "source_host" field.
func (u *RepositoryUpsert) SetSourceHost(v string) *RepositoryUpsert {
	u.Set(repository.FieldSourceHost, v)
	return u
}

// UpdateSourceHost sets the "source_host" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateSourceHost() *RepositoryUpsert {
	u.SetExcluded(repository.FieldSourceHost)
	return u
}

// SetRepositoryPath sets the "repository_path" field.
func (u *RepositoryUpsert) SetRepositoryPath(v string) *RepositoryUpsert {
	u.Set(repository.FieldRepositoryPath, v)
	return u
}

// UpdateRepositoryPath sets the "repository_path" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateRepositoryPath() *RepositoryUpsert {
	u.SetExcluded(repository.FieldRepositoryPath)
	return u
}

// SetRepositoryID sets the "repository_id" field.
func (u *RepositoryUpsert) SetRepositoryID(v string) *RepositoryUpsert {
	u.Set(repository.FieldRepositoryID, v)
	return u
}

// UpdateRepositoryID sets the "repository_id" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateRepositoryID() *RepositoryUpsert {
	u.SetExcluded(repository.FieldRepositoryID)
	return u
}

// SetDescription sets the "description" field.
func (u *RepositoryUpsert) SetDescription(v string) *RepositoryUpsert {
	u.Set(repository.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateDescription() *RepositoryUpsert {
	u.SetExcluded(repository.FieldDescription)
	return u
}

// SetStars sets the "stars" field.
func (u *RepositoryUpsert) SetStars(v int64) *RepositoryUpsert {
	u.Set(repository.FieldStars, v)
	return u
}

// UpdateStars sets the "stars" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateStars() *RepositoryUpsert {
	u.SetExcluded(repository.FieldStars)
	return u
}

// AddStars adds v to the "stars" field.
func (u *RepositoryUpsert) AddStars(v int64) *RepositoryUpsert {
	u.Add(repository.FieldStars, v)
	return u
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (u *RepositoryUpsert) SetSourceMetadataEtag(v string) *RepositoryUpsert {
	u.Set(repository.FieldSourceMetadataEtag, v)
	return u
}

// UpdateSourceMetadataEtag sets the "source_metadata_etag" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateSourceMetadataEtag() *RepositoryUpsert {
	u.SetExcluded(repository.FieldSourceMetadataEtag)
	return u
}

// ClearSourceMetadataEtag clears the value of the "source_metadata_etag" field.
func (u *RepositoryUpsert) ClearSourceMetadataEtag() *RepositoryUpsert {
	u.SetNull(repository.FieldSourceMetadataEtag)
	return u
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (u *RepositoryUpsert) SetSourceMetadataCheckedAt(v time.Time) *RepositoryUpsert {
	u.Set(repository.FieldSourceMetadataCheckedAt, v)
	return u
}

// UpdateSourceMetadataCheckedAt sets the "source_metadata_checked_at" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateSourceMetadataCheckedAt() *RepositoryUpsert {
	u.SetExcluded(repository.FieldSourceMetadataCheckedAt)
	return u
}

// ClearSourceMetadataCheckedAt clears the value of the "source_metadata_checked_at" field.
func (u *RepositoryUpsert) ClearSourceMetadataCheckedAt() *RepositoryUpsert {
	u.SetNull(repository.FieldSourceMetadataCheckedAt)
	return u
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (u *RepositoryUpsert) SetSourceMetadataRetryAt(v time.Time) *RepositoryUpsert {
	u.Set(repository.FieldSourceMetadataRetryAt, v)
	return u
}

// UpdateSourceMetadataRetryAt sets the "source_metadata_retry_at" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateSourceMetadataRetryAt() *RepositoryUpsert {
	u.SetExcluded(repository.FieldSourceMetadataRetryAt)
	return u
}

// ClearSourceMetadataRetryAt clears the value of the "source_metadata_retry_at" field.
func (u *RepositoryUpsert) ClearSourceMetadataRetryAt() *RepositoryUpsert {
	u.SetNull(repository.FieldSourceMetadataRetryAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RepositoryUpsert) SetCreatedAt(v time.Time) *RepositoryUpsert {
	u.Set(repository.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateCreatedAt() *RepositoryUpsert {
	u.SetExcluded(repository.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RepositoryUpsert) SetUpdatedAt(v time.Time) *RepositoryUpsert {
	u.Set(repository.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RepositoryUpsert) UpdateUpdatedAt() *RepositoryUpsert {
	u.SetExcluded(repository.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Repository.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(repository.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RepositoryUpsertOne) UpdateNewValues() *RepositoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(repository.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Repository.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RepositoryUpsertOne) Ignore() *RepositoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RepositoryUpsertOne) DoNothing() *RepositoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RepositoryCreate.OnConflict
// documentation for more info.
func (u *RepositoryUpsertOne) Update(set func(*RepositoryUpsert)) *RepositoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RepositoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceHost sets the "source_host" field.
func (u *RepositoryUpsertOne) SetSourceHost(v string) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceHost(v)
	})
}

// UpdateSourceHost sets the "source_host" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateSourceHost() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceHost()
	})
}

// SetRepositoryPath sets the "repository_path" field.
func (u *RepositoryUpsertOne) SetRepositoryPath(v string) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetRepositoryPath(v)
	})
}

// UpdateRepositoryPath sets the "repository_path" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateRepositoryPath() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateRepositoryPath()
	})
}

// SetRepositoryID sets the "repository_id" field.
func (u *RepositoryUpsertOne) SetRepositoryID(v string) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetRepositoryID(v)
	})
}

// UpdateRepositoryID sets the "repository_id" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateRepositoryID() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateRepositoryID()
	})
}

// SetDescription sets the "description" field.
func (u *RepositoryUpsertOne) SetDescription(v string) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateDescription() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateDescription()
	})
}

// SetStars sets the "stars" field.
func (u *RepositoryUpsertOne) SetStars(v int64) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetStars(v)
	})
}

// AddStars adds v to the "stars" field.
func (u *RepositoryUpsertOne) AddStars(v int64) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.AddStars(v)
	})
}

// UpdateStars sets the "stars" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateStars() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateStars()
	})
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (u *RepositoryUpsertOne) SetSourceMetadataEtag(v string) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataEtag(v)
	})
}

// UpdateSourceMetadataEtag sets the "source_metadata_etag" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateSourceMetadataEtag() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataEtag()
	})
}

// ClearSourceMetadataEtag clears the value of the "source_metadata_etag" field.
func (u *RepositoryUpsertOne) ClearSourceMetadataEtag() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataEtag()
	})
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (u *RepositoryUpsertOne) SetSourceMetadataCheckedAt(v time.Time) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataCheckedAt(v)
	})
}

// UpdateSourceMetadataCheckedAt sets the "source_metadata_checked_at" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateSourceMetadataCheckedAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataCheckedAt()
	})
}

// ClearSourceMetadataCheckedAt clears the value of the "source_metadata_checked_at" field.
func (u *RepositoryUpsertOne) ClearSourceMetadataCheckedAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataCheckedAt()
	})
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (u *RepositoryUpsertOne) SetSourceMetadataRetryAt(v time.Time) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataRetryAt(v)
	})
}

// UpdateSourceMetadataRetryAt sets the "source_metadata_retry_at" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateSourceMetadataRetryAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataRetryAt()
	})
}

// ClearSourceMetadataRetryAt clears the value of the "source_metadata_retry_at" field.
func (u *RepositoryUpsertOne) ClearSourceMetadataRetryAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataRetryAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RepositoryUpsertOne) SetCreatedAt(v time.Time) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateCreatedAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RepositoryUpsertOne) SetUpdatedAt(v time.Time) *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RepositoryUpsertOne) UpdateUpdatedAt() *RepositoryUpsertOne {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RepositoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RepositoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RepositoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RepositoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RepositoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RepositoryCreateBulk is the builder for creating many Repository entities in bulk.
type RepositoryCreateBulk struct {
	config
	err      error
	builders []*RepositoryCreate
	conflict []sql.ConflictOption
}

// Save creates the Repository entities in the database.
func (_c *RepositoryCreateBulk) Save(ctx context.Context) ([]*Repository, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repository, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryCreateBulk) SaveX(ctx context.Context) []*Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Repository.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RepositoryUpsert) {
//			SetSourceHost(v+v).
//		}).
//		Exec(ctx)
func (_c *RepositoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *RepositoryUpsertBulk {
	_c.conflict = opts
	return &RepositoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Repository.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RepositoryCreateBulk) OnConflictColumns(columns ...string) *RepositoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RepositoryUpsertBulk{
		create: _c,
	}
}

// RepositoryUpsertBulk is the builder for "upsert"-ing
// a bulk of Repository nodes.
type RepositoryUpsertBulk struct {
	create *RepositoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Repository.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(repository.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RepositoryUpsertBulk) UpdateNewValues() *RepositoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(repository.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Repository.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RepositoryUpsertBulk) Ignore() *RepositoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RepositoryUpsertBulk) DoNothing() *RepositoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RepositoryCreateBulk.OnConflict
// documentation for more info.
func (u *RepositoryUpsertBulk) Update(set func(*RepositoryUpsert)) *RepositoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RepositoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceHost sets the "source_host" field.
func (u *RepositoryUpsertBulk) SetSourceHost(v string) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceHost(v)
	})
}

// UpdateSourceHost sets the "source_host" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateSourceHost() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceHost()
	})
}

// SetRepositoryPath sets the "repository_path" field.
func (u *RepositoryUpsertBulk) SetRepositoryPath(v string) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetRepositoryPath(v)
	})
}

// UpdateRepositoryPath sets the "repository_path" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateRepositoryPath() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateRepositoryPath()
	})
}

// SetRepositoryID sets the "repository_id" field.
func (u *RepositoryUpsertBulk) SetRepositoryID(v string) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetRepositoryID(v)
	})
}

// UpdateRepositoryID sets the "repository_id" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateRepositoryID() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateRepositoryID()
	})
}

// SetDescription sets the "description" field.
func (u *RepositoryUpsertBulk) SetDescription(v string) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateDescription() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateDescription()
	})
}

// SetStars sets the "stars" field.
func (u *RepositoryUpsertBulk) SetStars(v int64) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetStars(v)
	})
}

// AddStars adds v to the "stars" field.
func (u *RepositoryUpsertBulk) AddStars(v int64) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.AddStars(v)
	})
}

// UpdateStars sets the "stars" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateStars() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateStars()
	})
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (u *RepositoryUpsertBulk) SetSourceMetadataEtag(v string) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataEtag(v)
	})
}

// UpdateSourceMetadataEtag sets the "source_metadata_etag" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateSourceMetadataEtag() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataEtag()
	})
}

// ClearSourceMetadataEtag clears the value of the "source_metadata_etag" field.
func (u *RepositoryUpsertBulk) ClearSourceMetadataEtag() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataEtag()
	})
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (u *RepositoryUpsertBulk) SetSourceMetadataCheckedAt(v time.Time) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataCheckedAt(v)
	})
}

// UpdateSourceMetadataCheckedAt sets the "source_metadata_checked_at" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateSourceMetadataCheckedAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataCheckedAt()
	})
}

// ClearSourceMetadataCheckedAt clears the value of the "source_metadata_checked_at" field.
func (u *RepositoryUpsertBulk) ClearSourceMetadataCheckedAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataCheckedAt()
	})
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (u *RepositoryUpsertBulk) SetSourceMetadataRetryAt(v time.Time) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetSourceMetadataRetryAt(v)
	})
}

// UpdateSourceMetadataRetryAt sets the "source_metadata_retry_at" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateSourceMetadataRetryAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateSourceMetadataRetryAt()
	})
}

// ClearSourceMetadataRetryAt clears the value of the "source_metadata_retry_at" field.
func (u *RepositoryUpsertBulk) ClearSourceMetadataRetryAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.ClearSourceMetadataRetryAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RepositoryUpsertBulk) SetCreatedAt(v time.Time) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateCreatedAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RepositoryUpsertBulk) SetUpdatedAt(v time.Time) *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RepositoryUpsertBulk) UpdateUpdatedAt() *RepositoryUpsertBulk {
	return u.Update(func(s *RepositoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RepositoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RepositoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RepositoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RepositoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
