// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryrelease"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryreleasemember"
)

// RepositoryReleaseMember is the model entity for the RepositoryReleaseMember schema.
type RepositoryReleaseMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ReleaseID holds the value of the "release_id" field.
	ReleaseID int64 `json:"release_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SkillPath holds the value of the "skill_path" field.
	SkillPath string `json:"skill_path,omitempty"`
	// TreeSha holds the value of the "tree_sha" field.
	TreeSha string `json:"tree_sha,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RepositoryReleaseMemberQuery when eager-loading is set.
	Edges        RepositoryReleaseMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RepositoryReleaseMemberEdges holds the relations/edges for other nodes in the graph.
type RepositoryReleaseMemberEdges struct {
	// Release holds the value of the release edge.
	Release *RepositoryRelease `json:"release,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReleaseOrErr returns the Release value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RepositoryReleaseMemberEdges) ReleaseOrErr() (*RepositoryRelease, error) {
	if e.Release != nil {
		return e.Release, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: repositoryrelease.Label}
	}
	return nil, &NotLoadedError{edge: "release"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepositoryReleaseMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repositoryreleasemember.FieldID, repositoryreleasemember.FieldReleaseID:
			values[i] = new(sql.NullInt64)
		case repositoryreleasemember.FieldName, repositoryreleasemember.FieldSkillPath, repositoryreleasemember.FieldTreeSha:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepositoryReleaseMember fields.
func (_m *RepositoryReleaseMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repositoryreleasemember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case repositoryreleasemember.FieldReleaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field release_id", values[i])
			} else if value.Valid {
				_m.ReleaseID = value.Int64
			}
		case repositoryreleasemember.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case repositoryreleasemember.FieldSkillPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_path", values[i])
			} else if value.Valid {
				_m.SkillPath = value.String
			}
		case repositoryreleasemember.FieldTreeSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tree_sha", values[i])
			} else if value.Valid {
				_m.TreeSha = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepositoryReleaseMember.
// This includes values selected through modifiers, order, etc.
func (_m *RepositoryReleaseMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRelease queries the "release" edge of the RepositoryReleaseMember entity.
func (_m *RepositoryReleaseMember) QueryRelease() *RepositoryReleaseQuery {
	return NewRepositoryReleaseMemberClient(_m.config).QueryRelease(_m)
}

// Update returns a builder for updating this RepositoryReleaseMember.
// Note that you need to call RepositoryReleaseMember.Unwrap() before calling this method if this RepositoryReleaseMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RepositoryReleaseMember) Update() *RepositoryReleaseMemberUpdateOne {
	return NewRepositoryReleaseMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RepositoryReleaseMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RepositoryReleaseMember) Unwrap() *RepositoryReleaseMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepositoryReleaseMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RepositoryReleaseMember) String() string {
	var builder strings.Builder
	builder.WriteString("RepositoryReleaseMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("release_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReleaseID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("skill_path=")
	builder.WriteString(_m.SkillPath)
	builder.WriteString(", ")
	builder.WriteString("tree_sha=")
	builder.WriteString(_m.TreeSha)
	builder.WriteByte(')')
	return builder.String()
}

// RepositoryReleaseMembers is a parsable slice of RepositoryReleaseMember.
type RepositoryReleaseMembers []*RepositoryReleaseMember
