// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repository"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryrelease"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceHost sets the "source_host" field.
func (_u *RepositoryUpdate) SetSourceHost(v string) *RepositoryUpdate {
	_u.mutation.SetSourceHost(v)
	return _u
}

// SetNillableSourceHost sets the "source_host" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSourceHost(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetSourceHost(*v)
	}
	return _u
}

// SetRepositoryPath sets the "repository_path" field.
func (_u *RepositoryUpdate) SetRepositoryPath(v string) *RepositoryUpdate {
	_u.mutation.SetRepositoryPath(v)
	return _u
}

// SetNillableRepositoryPath sets the "repository_path" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableRepositoryPath(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetRepositoryPath(*v)
	}
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *RepositoryUpdate) SetRepositoryID(v string) *RepositoryUpdate {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableRepositoryID(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetCurrentReleaseID sets the "current_release_id" field.
func (_u *RepositoryUpdate) SetCurrentReleaseID(v int64) *RepositoryUpdate {
	_u.mutation.SetCurrentReleaseID(v)
	return _u
}

// SetNillableCurrentReleaseID sets the "current_release_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableCurrentReleaseID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetCurrentReleaseID(*v)
	}
	return _u
}

// ClearCurrentReleaseID clears the value of the "current_release_id" field.
func (_u *RepositoryUpdate) ClearCurrentReleaseID() *RepositoryUpdate {
	_u.mutation.ClearCurrentReleaseID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdate) SetDescription(v string) *RepositoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDescription(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepositoryUpdate) SetStars(v int64) *RepositoryUpdate {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableStars(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepositoryUpdate) AddStars(v int64) *RepositoryUpdate {
	_u.mutation.AddStars(v)
	return _u
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (_u *RepositoryUpdate) SetSourceMetadataEtag(v string) *RepositoryUpdate {
	_u.mutation.SetSourceMetadataEtag(v)
	return _u
}

// SetNillableSourceMetadataEtag sets the "source_metadata_etag" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSourceMetadataEtag(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetSourceMetadataEtag(*v)
	}
	return _u
}

// ClearSourceMetadataEtag clears the value of the "source_metadata_etag" field.
func (_u *RepositoryUpdate) ClearSourceMetadataEtag() *RepositoryUpdate {
	_u.mutation.ClearSourceMetadataEtag()
	return _u
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (_u *RepositoryUpdate) SetSourceMetadataCheckedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetSourceMetadataCheckedAt(v)
	return _u
}

// SetNillableSourceMetadataCheckedAt sets the "source_metadata_checked_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSourceMetadataCheckedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetSourceMetadataCheckedAt(*v)
	}
	return _u
}

// ClearSourceMetadataCheckedAt clears the value of the "source_metadata_checked_at" field.
func (_u *RepositoryUpdate) ClearSourceMetadataCheckedAt() *RepositoryUpdate {
	_u.mutation.ClearSourceMetadataCheckedAt()
	return _u
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (_u *RepositoryUpdate) SetSourceMetadataRetryAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetSourceMetadataRetryAt(v)
	return _u
}

// SetNillableSourceMetadataRetryAt sets the "source_metadata_retry_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSourceMetadataRetryAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetSourceMetadataRetryAt(*v)
	}
	return _u
}

// ClearSourceMetadataRetryAt clears the value of the "source_metadata_retry_at" field.
func (_u *RepositoryUpdate) ClearSourceMetadataRetryAt() *RepositoryUpdate {
	_u.mutation.ClearSourceMetadataRetryAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdate) SetCreatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableCreatedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdate) SetUpdatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (_u *RepositoryUpdate) AddSkillIDs(ids ...int64) *RepositoryUpdate {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the Skill entity.
func (_u *RepositoryUpdate) AddSkills(v ...*Skill) *RepositoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// AddReleaseIDs adds the "releases" edge to the RepositoryRelease entity by IDs.
func (_u *RepositoryUpdate) AddReleaseIDs(ids ...int64) *RepositoryUpdate {
	_u.mutation.AddReleaseIDs(ids...)
	return _u
}

// AddReleases adds the "releases" edges to the RepositoryRelease entity.
func (_u *RepositoryUpdate) AddReleases(v ...*RepositoryRelease) *RepositoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReleaseIDs(ids...)
}

// SetCurrentRelease sets the "current_release" edge to the RepositoryRelease entity.
func (_u *RepositoryUpdate) SetCurrentRelease(v *RepositoryRelease) *RepositoryUpdate {
	return _u.SetCurrentReleaseID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (_u *RepositoryUpdate) ClearSkills() *RepositoryUpdate {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (_u *RepositoryUpdate) RemoveSkillIDs(ids ...int64) *RepositoryUpdate {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to Skill entities.
func (_u *RepositoryUpdate) RemoveSkills(v ...*Skill) *RepositoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// ClearReleases clears all "releases" edges to the RepositoryRelease entity.
func (_u *RepositoryUpdate) ClearReleases() *RepositoryUpdate {
	_u.mutation.ClearReleases()
	return _u
}

// RemoveReleaseIDs removes the "releases" edge to RepositoryRelease entities by IDs.
func (_u *RepositoryUpdate) RemoveReleaseIDs(ids ...int64) *RepositoryUpdate {
	_u.mutation.RemoveReleaseIDs(ids...)
	return _u
}

// RemoveReleases removes "releases" edges to RepositoryRelease entities.
func (_u *RepositoryUpdate) RemoveReleases(v ...*RepositoryRelease) *RepositoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReleaseIDs(ids...)
}

// ClearCurrentRelease clears the "current_release" edge to the RepositoryRelease entity.
func (_u *RepositoryUpdate) ClearCurrentRelease() *RepositoryUpdate {
	_u.mutation.ClearCurrentRelease()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdate) check() error {
	if v, ok := _u.mutation.SourceHost(); ok {
		if err := repository.SourceHostValidator(v); err != nil {
			return &ValidationError{Name: "source_host", err: fmt.Errorf(`ent: validator failed for field "Repository.source_host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepositoryPath(); ok {
		if err := repository.RepositoryPathValidator(v); err != nil {
			return &ValidationError{Name: "repository_path", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepositoryID(); ok {
		if err := repository.RepositoryIDValidator(v); err != nil {
			return &ValidationError{Name: "repository_id", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceHost(); ok {
		_spec.SetField(repository.FieldSourceHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryPath(); ok {
		_spec.SetField(repository.FieldRepositoryPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(repository.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repository.FieldStars, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repository.FieldStars, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceMetadataEtag(); ok {
		_spec.SetField(repository.FieldSourceMetadataEtag, field.TypeString, value)
	}
	if _u.mutation.SourceMetadataEtagCleared() {
		_spec.ClearField(repository.FieldSourceMetadataEtag, field.TypeString)
	}
	if value, ok := _u.mutation.SourceMetadataCheckedAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceMetadataCheckedAtCleared() {
		_spec.ClearField(repository.FieldSourceMetadataCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceMetadataRetryAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataRetryAt, field.TypeTime, value)
	}
	if _u.mutation.SourceMetadataRetryAtCleared() {
		_spec.ClearField(repository.FieldSourceMetadataRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReleasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReleasesIDs(); len(nodes) > 0 && !_u.mutation.ReleasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReleasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentReleaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   repository.CurrentReleaseTable,
			Columns: []string{repository.CurrentReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentReleaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   repository.CurrentReleaseTable,
			Columns: []string{repository.CurrentReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetSourceHost sets the "source_host" field.
func (_u *RepositoryUpdateOne) SetSourceHost(v string) *RepositoryUpdateOne {
	_u.mutation.SetSourceHost(v)
	return _u
}

// SetNillableSourceHost sets the "source_host" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSourceHost(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSourceHost(*v)
	}
	return _u
}

// SetRepositoryPath sets the "repository_path" field.
func (_u *RepositoryUpdateOne) SetRepositoryPath(v string) *RepositoryUpdateOne {
	_u.mutation.SetRepositoryPath(v)
	return _u
}

// SetNillableRepositoryPath sets the "repository_path" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableRepositoryPath(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetRepositoryPath(*v)
	}
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *RepositoryUpdateOne) SetRepositoryID(v string) *RepositoryUpdateOne {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableRepositoryID(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetCurrentReleaseID sets the "current_release_id" field.
func (_u *RepositoryUpdateOne) SetCurrentReleaseID(v int64) *RepositoryUpdateOne {
	_u.mutation.SetCurrentReleaseID(v)
	return _u
}

// SetNillableCurrentReleaseID sets the "current_release_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableCurrentReleaseID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetCurrentReleaseID(*v)
	}
	return _u
}

// ClearCurrentReleaseID clears the value of the "current_release_id" field.
func (_u *RepositoryUpdateOne) ClearCurrentReleaseID() *RepositoryUpdateOne {
	_u.mutation.ClearCurrentReleaseID()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdateOne) SetDescription(v string) *RepositoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDescription(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepositoryUpdateOne) SetStars(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableStars(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepositoryUpdateOne) AddStars(v int64) *RepositoryUpdateOne {
	_u.mutation.AddStars(v)
	return _u
}

// SetSourceMetadataEtag sets the "source_metadata_etag" field.
func (_u *RepositoryUpdateOne) SetSourceMetadataEtag(v string) *RepositoryUpdateOne {
	_u.mutation.SetSourceMetadataEtag(v)
	return _u
}

// SetNillableSourceMetadataEtag sets the "source_metadata_etag" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSourceMetadataEtag(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSourceMetadataEtag(*v)
	}
	return _u
}

// ClearSourceMetadataEtag clears the value of the "source_metadata_etag" field.
func (_u *RepositoryUpdateOne) ClearSourceMetadataEtag() *RepositoryUpdateOne {
	_u.mutation.ClearSourceMetadataEtag()
	return _u
}

// SetSourceMetadataCheckedAt sets the "source_metadata_checked_at" field.
func (_u *RepositoryUpdateOne) SetSourceMetadataCheckedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetSourceMetadataCheckedAt(v)
	return _u
}

// SetNillableSourceMetadataCheckedAt sets the "source_metadata_checked_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSourceMetadataCheckedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSourceMetadataCheckedAt(*v)
	}
	return _u
}

// ClearSourceMetadataCheckedAt clears the value of the "source_metadata_checked_at" field.
func (_u *RepositoryUpdateOne) ClearSourceMetadataCheckedAt() *RepositoryUpdateOne {
	_u.mutation.ClearSourceMetadataCheckedAt()
	return _u
}

// SetSourceMetadataRetryAt sets the "source_metadata_retry_at" field.
func (_u *RepositoryUpdateOne) SetSourceMetadataRetryAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetSourceMetadataRetryAt(v)
	return _u
}

// SetNillableSourceMetadataRetryAt sets the "source_metadata_retry_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSourceMetadataRetryAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSourceMetadataRetryAt(*v)
	}
	return _u
}

// ClearSourceMetadataRetryAt clears the value of the "source_metadata_retry_at" field.
func (_u *RepositoryUpdateOne) ClearSourceMetadataRetryAt() *RepositoryUpdateOne {
	_u.mutation.ClearSourceMetadataRetryAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdateOne) SetCreatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableCreatedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdateOne) SetUpdatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (_u *RepositoryUpdateOne) AddSkillIDs(ids ...int64) *RepositoryUpdateOne {
	_u.mutation.AddSkillIDs(ids...)
	return _u
}

// AddSkills adds the "skills" edges to the Skill entity.
func (_u *RepositoryUpdateOne) AddSkills(v ...*Skill) *RepositoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSkillIDs(ids...)
}

// AddReleaseIDs adds the "releases" edge to the RepositoryRelease entity by IDs.
func (_u *RepositoryUpdateOne) AddReleaseIDs(ids ...int64) *RepositoryUpdateOne {
	_u.mutation.AddReleaseIDs(ids...)
	return _u
}

// AddReleases adds the "releases" edges to the RepositoryRelease entity.
func (_u *RepositoryUpdateOne) AddReleases(v ...*RepositoryRelease) *RepositoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReleaseIDs(ids...)
}

// SetCurrentRelease sets the "current_release" edge to the RepositoryRelease entity.
func (_u *RepositoryUpdateOne) SetCurrentRelease(v *RepositoryRelease) *RepositoryUpdateOne {
	return _u.SetCurrentReleaseID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (_u *RepositoryUpdateOne) ClearSkills() *RepositoryUpdateOne {
	_u.mutation.ClearSkills()
	return _u
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (_u *RepositoryUpdateOne) RemoveSkillIDs(ids ...int64) *RepositoryUpdateOne {
	_u.mutation.RemoveSkillIDs(ids...)
	return _u
}

// RemoveSkills removes "skills" edges to Skill entities.
func (_u *RepositoryUpdateOne) RemoveSkills(v ...*Skill) *RepositoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSkillIDs(ids...)
}

// ClearReleases clears all "releases" edges to the RepositoryRelease entity.
func (_u *RepositoryUpdateOne) ClearReleases() *RepositoryUpdateOne {
	_u.mutation.ClearReleases()
	return _u
}

// RemoveReleaseIDs removes the "releases" edge to RepositoryRelease entities by IDs.
func (_u *RepositoryUpdateOne) RemoveReleaseIDs(ids ...int64) *RepositoryUpdateOne {
	_u.mutation.RemoveReleaseIDs(ids...)
	return _u
}

// RemoveReleases removes "releases" edges to RepositoryRelease entities.
func (_u *RepositoryUpdateOne) RemoveReleases(v ...*RepositoryRelease) *RepositoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReleaseIDs(ids...)
}

// ClearCurrentRelease clears the "current_release" edge to the RepositoryRelease entity.
func (_u *RepositoryUpdateOne) ClearCurrentRelease() *RepositoryUpdateOne {
	_u.mutation.ClearCurrentRelease()
	return _u
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdateOne) check() error {
	if v, ok := _u.mutation.SourceHost(); ok {
		if err := repository.SourceHostValidator(v); err != nil {
			return &ValidationError{Name: "source_host", err: fmt.Errorf(`ent: validator failed for field "Repository.source_host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepositoryPath(); ok {
		if err := repository.RepositoryPathValidator(v); err != nil {
			return &ValidationError{Name: "repository_path", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepositoryID(); ok {
		if err := repository.RepositoryIDValidator(v); err != nil {
			return &ValidationError{Name: "repository_id", err: fmt.Errorf(`ent: validator failed for field "Repository.repository_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceHost(); ok {
		_spec.SetField(repository.FieldSourceHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryPath(); ok {
		_spec.SetField(repository.FieldRepositoryPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(repository.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repository.FieldStars, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repository.FieldStars, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceMetadataEtag(); ok {
		_spec.SetField(repository.FieldSourceMetadataEtag, field.TypeString, value)
	}
	if _u.mutation.SourceMetadataEtagCleared() {
		_spec.ClearField(repository.FieldSourceMetadataEtag, field.TypeString)
	}
	if value, ok := _u.mutation.SourceMetadataCheckedAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.SourceMetadataCheckedAtCleared() {
		_spec.ClearField(repository.FieldSourceMetadataCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceMetadataRetryAt(); ok {
		_spec.SetField(repository.FieldSourceMetadataRetryAt, field.TypeTime, value)
	}
	if _u.mutation.SourceMetadataRetryAtCleared() {
		_spec.ClearField(repository.FieldSourceMetadataRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !_u.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.SkillsTable,
			Columns: []string{repository.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReleasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReleasesIDs(); len(nodes) > 0 && !_u.mutation.ReleasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReleasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ReleasesTable,
			Columns: []string{repository.ReleasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentReleaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   repository.CurrentReleaseTable,
			Columns: []string{repository.CurrentReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentReleaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   repository.CurrentReleaseTable,
			Columns: []string{repository.CurrentReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
