// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryreleasemember"
)

// RepositoryReleaseMemberDelete is the builder for deleting a RepositoryReleaseMember entity.
type RepositoryReleaseMemberDelete struct {
	config
	hooks    []Hook
	mutation *RepositoryReleaseMemberMutation
}

// Where appends a list predicates to the RepositoryReleaseMemberDelete builder.
func (_d *RepositoryReleaseMemberDelete) Where(ps ...predicate.RepositoryReleaseMember) *RepositoryReleaseMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RepositoryReleaseMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RepositoryReleaseMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RepositoryReleaseMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(repositoryreleasemember.Table, sqlgraph.NewFieldSpec(repositoryreleasemember.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RepositoryReleaseMemberDeleteOne is the builder for deleting a single RepositoryReleaseMember entity.
type RepositoryReleaseMemberDeleteOne struct {
	_d *RepositoryReleaseMemberDelete
}

// Where appends a list predicates to the RepositoryReleaseMemberDelete builder.
func (_d *RepositoryReleaseMemberDeleteOne) Where(ps ...predicate.RepositoryReleaseMember) *RepositoryReleaseMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RepositoryReleaseMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{repositoryreleasemember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RepositoryReleaseMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
