// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryrelease"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/repositoryreleasemember"
)

// RepositoryReleaseMemberCreate is the builder for creating a RepositoryReleaseMember entity.
type RepositoryReleaseMemberCreate struct {
	config
	mutation *RepositoryReleaseMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetReleaseID sets the "release_id" field.
func (_c *RepositoryReleaseMemberCreate) SetReleaseID(v int64) *RepositoryReleaseMemberCreate {
	_c.mutation.SetReleaseID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RepositoryReleaseMemberCreate) SetName(v string) *RepositoryReleaseMemberCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSkillPath sets the "skill_path" field.
func (_c *RepositoryReleaseMemberCreate) SetSkillPath(v string) *RepositoryReleaseMemberCreate {
	_c.mutation.SetSkillPath(v)
	return _c
}

// SetTreeSha sets the "tree_sha" field.
func (_c *RepositoryReleaseMemberCreate) SetTreeSha(v string) *RepositoryReleaseMemberCreate {
	_c.mutation.SetTreeSha(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RepositoryReleaseMemberCreate) SetID(v int64) *RepositoryReleaseMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRelease sets the "release" edge to the RepositoryRelease entity.
func (_c *RepositoryReleaseMemberCreate) SetRelease(v *RepositoryRelease) *RepositoryReleaseMemberCreate {
	return _c.SetReleaseID(v.ID)
}

// Mutation returns the RepositoryReleaseMemberMutation object of the builder.
func (_c *RepositoryReleaseMemberCreate) Mutation() *RepositoryReleaseMemberMutation {
	return _c.mutation
}

// Save creates the RepositoryReleaseMember in the database.
func (_c *RepositoryReleaseMemberCreate) Save(ctx context.Context) (*RepositoryReleaseMember, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryReleaseMemberCreate) SaveX(ctx context.Context) *RepositoryReleaseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryReleaseMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryReleaseMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryReleaseMemberCreate) check() error {
	if _, ok := _c.mutation.ReleaseID(); !ok {
		return &ValidationError{Name: "release_id", err: errors.New(`ent: missing required field "RepositoryReleaseMember.release_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RepositoryReleaseMember.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := repositoryreleasemember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RepositoryReleaseMember.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkillPath(); !ok {
		return &ValidationError{Name: "skill_path", err: errors.New(`ent: missing required field "RepositoryReleaseMember.skill_path"`)}
	}
	if v, ok := _c.mutation.SkillPath(); ok {
		if err := repositoryreleasemember.SkillPathValidator(v); err != nil {
			return &ValidationError{Name: "skill_path", err: fmt.Errorf(`ent: validator failed for field "RepositoryReleaseMember.skill_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TreeSha(); !ok {
		return &ValidationError{Name: "tree_sha", err: errors.New(`ent: missing required field "RepositoryReleaseMember.tree_sha"`)}
	}
	if v, ok := _c.mutation.TreeSha(); ok {
		if err := repositoryreleasemember.TreeShaValidator(v); err != nil {
			return &ValidationError{Name: "tree_sha", err: fmt.Errorf(`ent: validator failed for field "RepositoryReleaseMember.tree_sha": %w`, err)}
		}
	}
	if len(_c.mutation.ReleaseIDs()) == 0 {
		return &ValidationError{Name: "release", err: errors.New(`ent: missing required edge "RepositoryReleaseMember.release"`)}
	}
	return nil
}

func (_c *RepositoryReleaseMemberCreate) sqlSave(ctx context.Context) (*RepositoryReleaseMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryReleaseMemberCreate) createSpec() (*RepositoryReleaseMember, *sqlgraph.CreateSpec) {
	var (
		_node = &RepositoryReleaseMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repositoryreleasemember.Table, sqlgraph.NewFieldSpec(repositoryreleasemember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repositoryreleasemember.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SkillPath(); ok {
		_spec.SetField(repositoryreleasemember.FieldSkillPath, field.TypeString, value)
		_node.SkillPath = value
	}
	if value, ok := _c.mutation.TreeSha(); ok {
		_spec.SetField(repositoryreleasemember.FieldTreeSha, field.TypeString, value)
		_node.TreeSha = value
	}
	if nodes := _c.mutation.ReleaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repositoryreleasemember.ReleaseTable,
			Columns: []string{repositoryreleasemember.ReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repositoryrelease.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReleaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RepositoryReleaseMember.Create().
//		SetReleaseID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RepositoryReleaseMemberUpsert) {
//			SetReleaseID(v+v).
//		}).
//		Exec(ctx)
func (_c *RepositoryReleaseMemberCreate) OnConflict(opts ...sql.ConflictOption) *RepositoryReleaseMemberUpsertOne {
	_c.conflict = opts
	return &RepositoryReleaseMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RepositoryReleaseMemberCreate) OnConflictColumns(columns ...string) *RepositoryReleaseMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RepositoryReleaseMemberUpsertOne{
		create: _c,
	}
}

type (
	// RepositoryReleaseMemberUpsertOne is the builder for "upsert"-ing
	//  one RepositoryReleaseMember node.
	RepositoryReleaseMemberUpsertOne struct {
		create *RepositoryReleaseMemberCreate
	}

	// RepositoryReleaseMemberUpsert is the "OnConflict" setter.
	RepositoryReleaseMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetReleaseID sets the "release_id" field.
func (u *RepositoryReleaseMemberUpsert) SetReleaseID(v int64) *RepositoryReleaseMemberUpsert {
	u.Set(repositoryreleasemember.FieldReleaseID, v)
	return u
}

// UpdateReleaseID sets the "release_id" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsert) UpdateReleaseID() *RepositoryReleaseMemberUpsert {
	u.SetExcluded(repositoryreleasemember.FieldReleaseID)
	return u
}

// SetName sets the "name" field.
func (u *RepositoryReleaseMemberUpsert) SetName(v string) *RepositoryReleaseMemberUpsert {
	u.Set(repositoryreleasemember.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsert) UpdateName() *RepositoryReleaseMemberUpsert {
	u.SetExcluded(repositoryreleasemember.FieldName)
	return u
}

// SetSkillPath sets the "skill_path" field.
func (u *RepositoryReleaseMemberUpsert) SetSkillPath(v string) *RepositoryReleaseMemberUpsert {
	u.Set(repositoryreleasemember.FieldSkillPath, v)
	return u
}

// UpdateSkillPath sets the "skill_path" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsert) UpdateSkillPath() *RepositoryReleaseMemberUpsert {
	u.SetExcluded(repositoryreleasemember.FieldSkillPath)
	return u
}

// SetTreeSha sets the "tree_sha" field.
func (u *RepositoryReleaseMemberUpsert) SetTreeSha(v string) *RepositoryReleaseMemberUpsert {
	u.Set(repositoryreleasemember.FieldTreeSha, v)
	return u
}

// UpdateTreeSha sets the "tree_sha" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsert) UpdateTreeSha() *RepositoryReleaseMemberUpsert {
	u.SetExcluded(repositoryreleasemember.FieldTreeSha)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(repositoryreleasemember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RepositoryReleaseMemberUpsertOne) UpdateNewValues() *RepositoryReleaseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(repositoryreleasemember.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RepositoryReleaseMemberUpsertOne) Ignore() *RepositoryReleaseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RepositoryReleaseMemberUpsertOne) DoNothing() *RepositoryReleaseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RepositoryReleaseMemberCreate.OnConflict
// documentation for more info.
func (u *RepositoryReleaseMemberUpsertOne) Update(set func(*RepositoryReleaseMemberUpsert)) *RepositoryReleaseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RepositoryReleaseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetReleaseID sets the "release_id" field.
func (u *RepositoryReleaseMemberUpsertOne) SetReleaseID(v int64) *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetReleaseID(v)
	})
}

// UpdateReleaseID sets the "release_id" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertOne) UpdateReleaseID() *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateReleaseID()
	})
}

// SetName sets the "name" field.
func (u *RepositoryReleaseMemberUpsertOne) SetName(v string) *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertOne) UpdateName() *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateName()
	})
}

// SetSkillPath sets the "skill_path" field.
func (u *RepositoryReleaseMemberUpsertOne) SetSkillPath(v string) *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetSkillPath(v)
	})
}

// UpdateSkillPath sets the "skill_path" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertOne) UpdateSkillPath() *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateSkillPath()
	})
}

// SetTreeSha sets the "tree_sha" field.
func (u *RepositoryReleaseMemberUpsertOne) SetTreeSha(v string) *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetTreeSha(v)
	})
}

// UpdateTreeSha sets the "tree_sha" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertOne) UpdateTreeSha() *RepositoryReleaseMemberUpsertOne {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateTreeSha()
	})
}

// Exec executes the query.
func (u *RepositoryReleaseMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RepositoryReleaseMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RepositoryReleaseMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RepositoryReleaseMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RepositoryReleaseMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RepositoryReleaseMemberCreateBulk is the builder for creating many RepositoryReleaseMember entities in bulk.
type RepositoryReleaseMemberCreateBulk struct {
	config
	err      error
	builders []*RepositoryReleaseMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the RepositoryReleaseMember entities in the database.
func (_c *RepositoryReleaseMemberCreateBulk) Save(ctx context.Context) ([]*RepositoryReleaseMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RepositoryReleaseMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryReleaseMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryReleaseMemberCreateBulk) SaveX(ctx context.Context) []*RepositoryReleaseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryReleaseMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryReleaseMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RepositoryReleaseMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RepositoryReleaseMemberUpsert) {
//			SetReleaseID(v+v).
//		}).
//		Exec(ctx)
func (_c *RepositoryReleaseMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *RepositoryReleaseMemberUpsertBulk {
	_c.conflict = opts
	return &RepositoryReleaseMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RepositoryReleaseMemberCreateBulk) OnConflictColumns(columns ...string) *RepositoryReleaseMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RepositoryReleaseMemberUpsertBulk{
		create: _c,
	}
}

// RepositoryReleaseMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of RepositoryReleaseMember nodes.
type RepositoryReleaseMemberUpsertBulk struct {
	create *RepositoryReleaseMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(repositoryreleasemember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RepositoryReleaseMemberUpsertBulk) UpdateNewValues() *RepositoryReleaseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(repositoryreleasemember.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RepositoryReleaseMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RepositoryReleaseMemberUpsertBulk) Ignore() *RepositoryReleaseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RepositoryReleaseMemberUpsertBulk) DoNothing() *RepositoryReleaseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RepositoryReleaseMemberCreateBulk.OnConflict
// documentation for more info.
func (u *RepositoryReleaseMemberUpsertBulk) Update(set func(*RepositoryReleaseMemberUpsert)) *RepositoryReleaseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RepositoryReleaseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetReleaseID sets the "release_id" field.
func (u *RepositoryReleaseMemberUpsertBulk) SetReleaseID(v int64) *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetReleaseID(v)
	})
}

// UpdateReleaseID sets the "release_id" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertBulk) UpdateReleaseID() *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateReleaseID()
	})
}

// SetName sets the "name" field.
func (u *RepositoryReleaseMemberUpsertBulk) SetName(v string) *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertBulk) UpdateName() *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateName()
	})
}

// SetSkillPath sets the "skill_path" field.
func (u *RepositoryReleaseMemberUpsertBulk) SetSkillPath(v string) *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetSkillPath(v)
	})
}

// UpdateSkillPath sets the "skill_path" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertBulk) UpdateSkillPath() *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateSkillPath()
	})
}

// SetTreeSha sets the "tree_sha" field.
func (u *RepositoryReleaseMemberUpsertBulk) SetTreeSha(v string) *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.SetTreeSha(v)
	})
}

// UpdateTreeSha sets the "tree_sha" field to the value that was provided on create.
func (u *RepositoryReleaseMemberUpsertBulk) UpdateTreeSha() *RepositoryReleaseMemberUpsertBulk {
	return u.Update(func(s *RepositoryReleaseMemberUpsert) {
		s.UpdateTreeSha()
	})
}

// Exec executes the query.
func (u *RepositoryReleaseMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RepositoryReleaseMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RepositoryReleaseMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RepositoryReleaseMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
