// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/riskassessment"
)

// RiskAssessmentDelete is the builder for deleting a RiskAssessment entity.
type RiskAssessmentDelete struct {
	config
	hooks    []Hook
	mutation *RiskAssessmentMutation
}

// Where appends a list predicates to the RiskAssessmentDelete builder.
func (_d *RiskAssessmentDelete) Where(ps ...predicate.RiskAssessment) *RiskAssessmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RiskAssessmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RiskAssessmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RiskAssessmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(riskassessment.Table, sqlgraph.NewFieldSpec(riskassessment.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RiskAssessmentDeleteOne is the builder for deleting a single RiskAssessment entity.
type RiskAssessmentDeleteOne struct {
	_d *RiskAssessmentDelete
}

// Where appends a list predicates to the RiskAssessmentDelete builder.
func (_d *RiskAssessmentDeleteOne) Where(ps ...predicate.RiskAssessment) *RiskAssessmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RiskAssessmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{riskassessment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RiskAssessmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
