// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/installevent"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/riskassessment"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/schema"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillhourlystat"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillstat"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillversion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	installeventFields := schema.InstallEvent{}.Fields()
	_ = installeventFields
	// installeventDescReceivedAt is the schema descriptor for received_at field.
	installeventDescReceivedAt := installeventFields[7].Descriptor()
	// installevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	installevent.DefaultReceivedAt = installeventDescReceivedAt.Default.(func() time.Time)
	riskassessmentFields := schema.RiskAssessment{}.Fields()
	_ = riskassessmentFields
	// riskassessmentDescLevel is the schema descriptor for level field.
	riskassessmentDescLevel := riskassessmentFields[2].Descriptor()
	// riskassessment.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	riskassessment.LevelValidator = riskassessmentDescLevel.Validators[0].(func(string) error)
	// riskassessmentDescScannerVersion is the schema descriptor for scanner_version field.
	riskassessmentDescScannerVersion := riskassessmentFields[3].Descriptor()
	// riskassessment.ScannerVersionValidator is a validator for the "scanner_version" field. It is called by the builders before save.
	riskassessment.ScannerVersionValidator = riskassessmentDescScannerVersion.Validators[0].(func(string) error)
	// riskassessmentDescEvidence is the schema descriptor for evidence field.
	riskassessmentDescEvidence := riskassessmentFields[4].Descriptor()
	// riskassessment.EvidenceValidator is a validator for the "evidence" field. It is called by the builders before save.
	riskassessment.EvidenceValidator = riskassessmentDescEvidence.Validators[0].(func(string) error)
	// riskassessmentDescFingerprint is the schema descriptor for fingerprint field.
	riskassessmentDescFingerprint := riskassessmentFields[5].Descriptor()
	// riskassessment.FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	riskassessment.FingerprintValidator = riskassessmentDescFingerprint.Validators[0].(func(string) error)
	// riskassessmentDescCreatedAt is the schema descriptor for created_at field.
	riskassessmentDescCreatedAt := riskassessmentFields[6].Descriptor()
	// riskassessment.DefaultCreatedAt holds the default value on creation for the created_at field.
	riskassessment.DefaultCreatedAt = riskassessmentDescCreatedAt.Default.(func() time.Time)
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescSkillID is the schema descriptor for skill_id field.
	skillDescSkillID := skillFields[1].Descriptor()
	// skill.SkillIDValidator is a validator for the "skill_id" field. It is called by the builders before save.
	skill.SkillIDValidator = skillDescSkillID.Validators[0].(func(string) error)
	// skillDescGithubStars is the schema descriptor for github_stars field.
	skillDescGithubStars := skillFields[8].Descriptor()
	// skill.DefaultGithubStars holds the default value on creation for the github_stars field.
	skill.DefaultGithubStars = skillDescGithubStars.Default.(int64)
	// skillDescVerified is the schema descriptor for verified field.
	skillDescVerified := skillFields[9].Descriptor()
	// skill.DefaultVerified holds the default value on creation for the verified field.
	skill.DefaultVerified = skillDescVerified.Default.(bool)
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillFields[10].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillFields[11].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	// skill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	skill.UpdateDefaultUpdatedAt = skillDescUpdatedAt.UpdateDefault.(func() time.Time)
	skillhourlystatFields := schema.SkillHourlyStat{}.Fields()
	_ = skillhourlystatFields
	// skillhourlystatDescInstalls is the schema descriptor for installs field.
	skillhourlystatDescInstalls := skillhourlystatFields[3].Descriptor()
	// skillhourlystat.DefaultInstalls holds the default value on creation for the installs field.
	skillhourlystat.DefaultInstalls = skillhourlystatDescInstalls.Default.(int64)
	skillstatFields := schema.SkillStat{}.Fields()
	_ = skillstatFields
	// skillstatDescTotalInstalls is the schema descriptor for total_installs field.
	skillstatDescTotalInstalls := skillstatFields[1].Descriptor()
	// skillstat.DefaultTotalInstalls holds the default value on creation for the total_installs field.
	skillstat.DefaultTotalInstalls = skillstatDescTotalInstalls.Default.(int64)
	skillversionFields := schema.SkillVersion{}.Fields()
	_ = skillversionFields
	// skillversionDescVersion is the schema descriptor for version field.
	skillversionDescVersion := skillversionFields[2].Descriptor()
	// skillversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	skillversion.VersionValidator = skillversionDescVersion.Validators[0].(func(string) error)
	// skillversionDescCommitSha is the schema descriptor for commit_sha field.
	skillversionDescCommitSha := skillversionFields[3].Descriptor()
	// skillversion.CommitShaValidator is a validator for the "commit_sha" field. It is called by the builders before save.
	skillversion.CommitShaValidator = skillversionDescCommitSha.Validators[0].(func(string) error)
	// skillversionDescTreeSha is the schema descriptor for tree_sha field.
	skillversionDescTreeSha := skillversionFields[4].Descriptor()
	// skillversion.TreeShaValidator is a validator for the "tree_sha" field. It is called by the builders before save.
	skillversion.TreeShaValidator = skillversionDescTreeSha.Validators[0].(func(string) error)
	// skillversionDescContentDigest is the schema descriptor for content_digest field.
	skillversionDescContentDigest := skillversionFields[5].Descriptor()
	// skillversion.ContentDigestValidator is a validator for the "content_digest" field. It is called by the builders before save.
	skillversion.ContentDigestValidator = skillversionDescContentDigest.Validators[0].(func(string) error)
	// skillversionDescArchiveSize is the schema descriptor for archive_size field.
	skillversionDescArchiveSize := skillversionFields[7].Descriptor()
	// skillversion.DefaultArchiveSize holds the default value on creation for the archive_size field.
	skillversion.DefaultArchiveSize = skillversionDescArchiveSize.Default.(int64)
	// skillversionDescCreatedAt is the schema descriptor for created_at field.
	skillversionDescCreatedAt := skillversionFields[8].Descriptor()
	// skillversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	skillversion.DefaultCreatedAt = skillversionDescCreatedAt.Default.(func() time.Time)
}
