// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/predicate"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillhourlystat"
)

// SkillHourlyStatQuery is the builder for querying SkillHourlyStat entities.
type SkillHourlyStatQuery struct {
	config
	ctx        *QueryContext
	order      []skillhourlystat.OrderOption
	inters     []Interceptor
	predicates []predicate.SkillHourlyStat
	withSkill  *SkillQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SkillHourlyStatQuery builder.
func (_q *SkillHourlyStatQuery) Where(ps ...predicate.SkillHourlyStat) *SkillHourlyStatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SkillHourlyStatQuery) Limit(limit int) *SkillHourlyStatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SkillHourlyStatQuery) Offset(offset int) *SkillHourlyStatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SkillHourlyStatQuery) Unique(unique bool) *SkillHourlyStatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SkillHourlyStatQuery) Order(o ...skillhourlystat.OrderOption) *SkillHourlyStatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySkill chains the current query on the "skill" edge.
func (_q *SkillHourlyStatQuery) QuerySkill() *SkillQuery {
	query := (&SkillClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(skillhourlystat.Table, skillhourlystat.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, skillhourlystat.SkillTable, skillhourlystat.SkillColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SkillHourlyStat entity from the query.
// Returns a *NotFoundError when no SkillHourlyStat was found.
func (_q *SkillHourlyStatQuery) First(ctx context.Context) (*SkillHourlyStat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{skillhourlystat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) FirstX(ctx context.Context) *SkillHourlyStat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SkillHourlyStat ID from the query.
// Returns a *NotFoundError when no SkillHourlyStat ID was found.
func (_q *SkillHourlyStatQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{skillhourlystat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SkillHourlyStat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SkillHourlyStat entity is found.
// Returns a *NotFoundError when no SkillHourlyStat entities are found.
func (_q *SkillHourlyStatQuery) Only(ctx context.Context) (*SkillHourlyStat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{skillhourlystat.Label}
	default:
		return nil, &NotSingularError{skillhourlystat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) OnlyX(ctx context.Context) *SkillHourlyStat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SkillHourlyStat ID in the query.
// Returns a *NotSingularError when more than one SkillHourlyStat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SkillHourlyStatQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{skillhourlystat.Label}
	default:
		err = &NotSingularError{skillhourlystat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SkillHourlyStats.
func (_q *SkillHourlyStatQuery) All(ctx context.Context) ([]*SkillHourlyStat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SkillHourlyStat, *SkillHourlyStatQuery]()
	return withInterceptors[[]*SkillHourlyStat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) AllX(ctx context.Context) []*SkillHourlyStat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SkillHourlyStat IDs.
func (_q *SkillHourlyStatQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(skillhourlystat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SkillHourlyStatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SkillHourlyStatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SkillHourlyStatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SkillHourlyStatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SkillHourlyStatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SkillHourlyStatQuery) Clone() *SkillHourlyStatQuery {
	if _q == nil {
		return nil
	}
	return &SkillHourlyStatQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]skillhourlystat.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SkillHourlyStat{}, _q.predicates...),
		withSkill:  _q.withSkill.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSkill tells the query-builder to eager-load the nodes that are connected to
// the "skill" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SkillHourlyStatQuery) WithSkill(opts ...func(*SkillQuery)) *SkillHourlyStatQuery {
	query := (&SkillClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSkill = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SkillID int64 `json:"skill_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SkillHourlyStat.Query().
//		GroupBy(skillhourlystat.FieldSkillID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SkillHourlyStatQuery) GroupBy(field string, fields ...string) *SkillHourlyStatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SkillHourlyStatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = skillhourlystat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SkillID int64 `json:"skill_id,omitempty"`
//	}
//
//	client.SkillHourlyStat.Query().
//		Select(skillhourlystat.FieldSkillID).
//		Scan(ctx, &v)
func (_q *SkillHourlyStatQuery) Select(fields ...string) *SkillHourlyStatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SkillHourlyStatSelect{SkillHourlyStatQuery: _q}
	sbuild.label = skillhourlystat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SkillHourlyStatSelect configured with the given aggregations.
func (_q *SkillHourlyStatQuery) Aggregate(fns ...AggregateFunc) *SkillHourlyStatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SkillHourlyStatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !skillhourlystat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SkillHourlyStatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SkillHourlyStat, error) {
	var (
		nodes       = []*SkillHourlyStat{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSkill != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SkillHourlyStat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SkillHourlyStat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSkill; query != nil {
		if err := _q.loadSkill(ctx, query, nodes, nil,
			func(n *SkillHourlyStat, e *Skill) { n.Edges.Skill = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SkillHourlyStatQuery) loadSkill(ctx context.Context, query *SkillQuery, nodes []*SkillHourlyStat, init func(*SkillHourlyStat), assign func(*SkillHourlyStat, *Skill)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SkillHourlyStat)
	for i := range nodes {
		fk := nodes[i].SkillID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(skill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "skill_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SkillHourlyStatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SkillHourlyStatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(skillhourlystat.Table, skillhourlystat.Columns, sqlgraph.NewFieldSpec(skillhourlystat.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skillhourlystat.FieldID)
		for i := range fields {
			if fields[i] != skillhourlystat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSkill != nil {
			_spec.Node.AddColumnOnce(skillhourlystat.FieldSkillID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SkillHourlyStatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(skillhourlystat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = skillhourlystat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SkillHourlyStatGroupBy is the group-by builder for SkillHourlyStat entities.
type SkillHourlyStatGroupBy struct {
	selector
	build *SkillHourlyStatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SkillHourlyStatGroupBy) Aggregate(fns ...AggregateFunc) *SkillHourlyStatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SkillHourlyStatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SkillHourlyStatQuery, *SkillHourlyStatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SkillHourlyStatGroupBy) sqlScan(ctx context.Context, root *SkillHourlyStatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SkillHourlyStatSelect is the builder for selecting fields of SkillHourlyStat entities.
type SkillHourlyStatSelect struct {
	*SkillHourlyStatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SkillHourlyStatSelect) Aggregate(fns ...AggregateFunc) *SkillHourlyStatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SkillHourlyStatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SkillHourlyStatQuery, *SkillHourlyStatSelect](ctx, _s.SkillHourlyStatQuery, _s, _s.inters, v)
}

func (_s *SkillHourlyStatSelect) sqlScan(ctx context.Context, root *SkillHourlyStatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
