// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skill"
	"github.com/skillsgo/skillsgo/hub/pkg/catalog/ent/skillhourlystat"
)

// SkillHourlyStat is the model entity for the SkillHourlyStat schema.
type SkillHourlyStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID int64 `json:"skill_id,omitempty"`
	// Bucket holds the value of the "bucket" field.
	Bucket time.Time `json:"bucket,omitempty"`
	// Installs holds the value of the "installs" field.
	Installs int64 `json:"installs,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SkillHourlyStatQuery when eager-loading is set.
	Edges        SkillHourlyStatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SkillHourlyStatEdges holds the relations/edges for other nodes in the graph.
type SkillHourlyStatEdges struct {
	// Skill holds the value of the skill edge.
	Skill *Skill `json:"skill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillHourlyStatEdges) SkillOrErr() (*Skill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SkillHourlyStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skillhourlystat.FieldID, skillhourlystat.FieldSkillID, skillhourlystat.FieldInstalls:
			values[i] = new(sql.NullInt64)
		case skillhourlystat.FieldBucket:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SkillHourlyStat fields.
func (_m *SkillHourlyStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skillhourlystat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case skillhourlystat.FieldSkillID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.Int64
			}
		case skillhourlystat.FieldBucket:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.Time
			}
		case skillhourlystat.FieldInstalls:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field installs", values[i])
			} else if value.Valid {
				_m.Installs = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SkillHourlyStat.
// This includes values selected through modifiers, order, etc.
func (_m *SkillHourlyStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySkill queries the "skill" edge of the SkillHourlyStat entity.
func (_m *SkillHourlyStat) QuerySkill() *SkillQuery {
	return NewSkillHourlyStatClient(_m.config).QuerySkill(_m)
}

// Update returns a builder for updating this SkillHourlyStat.
// Note that you need to call SkillHourlyStat.Unwrap() before calling this method if this SkillHourlyStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SkillHourlyStat) Update() *SkillHourlyStatUpdateOne {
	return NewSkillHourlyStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SkillHourlyStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SkillHourlyStat) Unwrap() *SkillHourlyStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SkillHourlyStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SkillHourlyStat) String() string {
	var builder strings.Builder
	builder.WriteString("SkillHourlyStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("installs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Installs))
	builder.WriteByte(')')
	return builder.String()
}

// SkillHourlyStats is a parsable slice of SkillHourlyStat.
type SkillHourlyStats []*SkillHourlyStat
