// Code generated by ent, DO NOT EDIT.

package installevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the installevent type in the database.
	Label = "install_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "event_id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldAgents holds the string denoting the agents field in the database.
	FieldAgents = "agents"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldCliVersion holds the string denoting the cli_version field in the database.
	FieldCliVersion = "cli_version"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// SkillFieldID holds the string denoting the ID field of the Skill.
	SkillFieldID = "id"
	// Table holds the table name of the installevent in the database.
	Table = "install_events"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "install_events"
	// SkillInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillInverseTable = "skills"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
)

// Columns holds all SQL columns for installevent fields.
var Columns = []string{
	FieldID,
	FieldSkillID,
	FieldVersion,
	FieldAgents,
	FieldScope,
	FieldCliVersion,
	FieldOccurredAt,
	FieldReceivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
)

// OrderOption defines the ordering options for the InstallEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByAgents orders the results by the agents field.
func ByAgents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgents, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByCliVersion orders the results by the cli_version field.
func ByCliVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCliVersion, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, SkillFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
	)
}
