// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBackfillRun = `-- name: ActiveBackfillRun :one
SELECT id, module_path, status, started_at, completed_at, error_count, diagnostics, created_at, updated_at FROM module_backfill_runs
WHERE module_path=$1 AND status IN ('queued','running')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) ActiveBackfillRun(ctx context.Context, modulePath string) (ModuleBackfillRun, error) {
	row := q.db.QueryRow(ctx, activeBackfillRun, modulePath)
	var i ModuleBackfillRun
	err := row.Scan(
		&i.ID,
		&i.ModulePath,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCount,
		&i.Diagnostics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillRunByID = `-- name: BackfillRunByID :one
SELECT id, module_path, status, started_at, completed_at, error_count, diagnostics, created_at, updated_at FROM module_backfill_runs WHERE id=$1
`

func (q *Queries) BackfillRunByID(ctx context.Context, id string) (ModuleBackfillRun, error) {
	row := q.db.QueryRow(ctx, backfillRunByID, id)
	var i ModuleBackfillRun
	err := row.Scan(
		&i.ID,
		&i.ModulePath,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCount,
		&i.Diagnostics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeBackfillRun = `-- name: CompleteBackfillRun :execrows
UPDATE module_backfill_runs SET status=$2,completed_at=$3,error_count=$4,diagnostics=$5,updated_at=$3
WHERE id=$1 AND status IN ('queued','running')
`

type CompleteBackfillRunParams struct {
	ID          string          `json:"id"`
	Status      string          `json:"status"`
	CompletedAt *time.Time      `json:"completed_at"`
	ErrorCount  int32           `json:"error_count"`
	Diagnostics json.RawMessage `json:"diagnostics"`
}

func (q *Queries) CompleteBackfillRun(ctx context.Context, arg CompleteBackfillRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeBackfillRun,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorCount,
		arg.Diagnostics,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const currentSkill = `-- name: CurrentSkill :one
SELECT mvs.version_id, mvs.name, mv.version, mv.commit_sha,
       mvs.path, mv.commit_time, mvs.description
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
WHERE m.path=$1 AND mvs.name=$2
ORDER BY mvs.path
LIMIT 1
`

type CurrentSkillParams struct {
	ModulePath string `json:"module_path"`
	Name       string `json:"name"`
}

type CurrentSkillRow struct {
	VersionID   int64     `json:"version_id"`
	Name        string    `json:"name"`
	Version     string    `json:"version"`
	CommitSha   string    `json:"commit_sha"`
	Path        string    `json:"path"`
	CommitTime  time.Time `json:"commit_time"`
	Description string    `json:"description"`
}

func (q *Queries) CurrentSkill(ctx context.Context, arg CurrentSkillParams) (CurrentSkillRow, error) {
	row := q.db.QueryRow(ctx, currentSkill, arg.ModulePath, arg.Name)
	var i CurrentSkillRow
	err := row.Scan(
		&i.VersionID,
		&i.Name,
		&i.Version,
		&i.CommitSha,
		&i.Path,
		&i.CommitTime,
		&i.Description,
	)
	return i, err
}

const expireQueuedBackfillRun = `-- name: ExpireQueuedBackfillRun :execrows
UPDATE module_backfill_runs SET status='complete_with_errors',completed_at=$2,error_count=error_count+1,diagnostics=$3,updated_at=$2
WHERE id=$1 AND status='queued'
`

type ExpireQueuedBackfillRunParams struct {
	ID          string          `json:"id"`
	CompletedAt *time.Time      `json:"completed_at"`
	Diagnostics json.RawMessage `json:"diagnostics"`
}

func (q *Queries) ExpireQueuedBackfillRun(ctx context.Context, arg ExpireQueuedBackfillRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireQueuedBackfillRun, arg.ID, arg.CompletedAt, arg.Diagnostics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStaleBackfillRuns = `-- name: ExpireStaleBackfillRuns :execrows
UPDATE module_backfill_runs SET status='complete_with_errors',completed_at=$2,error_count=error_count+1,diagnostics=$3,updated_at=$2
WHERE status='running' AND updated_at<$1
`

type ExpireStaleBackfillRunsParams struct {
	UpdatedAt   time.Time       `json:"updated_at"`
	CompletedAt *time.Time      `json:"completed_at"`
	Diagnostics json.RawMessage `json:"diagnostics"`
}

func (q *Queries) ExpireStaleBackfillRuns(ctx context.Context, arg ExpireStaleBackfillRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleBackfillRuns, arg.UpdatedAt, arg.CompletedAt, arg.Diagnostics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findExactLocalizedSkillsBatch = `-- name: FindExactLocalizedSkillsBatch :many
WITH requested AS (
    SELECT ids.id AS query_id, queries.query, module_paths.module_path, ids.ordinal
    FROM unnest($2::text[]) WITH ORDINALITY AS ids(id, ordinal)
    JOIN unnest($3::text[]) WITH ORDINALITY AS queries(query, ordinal) USING (ordinal)
    JOIN unnest($4::text[]) WITH ORDINALITY AS module_paths(module_path, ordinal) USING (ordinal)
),
ranked AS (
    SELECT input.query_id::text AS query_id,input.query::text AS query,input.module_path::text AS requested_module_path,input.ordinal,
           mvs.version_id AS id,mv.module_id,m.path AS module_path,mvs.name,
           COALESCE(ls.description,mvs.description) AS description,
           m.source_host,m.source_path AS source_repository,mvs.path,
           mv.version AS latest_version,m.stars,mv.created_at,m.updated_at,
           row_number() OVER (
               PARTITION BY input.ordinal
               ORDER BY CASE WHEN input.module_path<>'' THEN mvs.path ELSE '' END,
                        m.path,mvs.path
           ) AS result_ordinal
    FROM requested input
    JOIN modules m ON input.module_path='' OR m.path=input.module_path
    JOIN versions mv ON mv.id=m.current_version_id
    JOIN skills mvs
      ON mvs.version_id=mv.id AND lower(mvs.name)=lower(input.query)
    LEFT JOIN localized_descriptions ls
      ON ls.resource_kind='skill' AND ls.resource_id=m.path || ':' || mvs.name AND ls.locale=$5
)
SELECT query_id,query,requested_module_path,id,module_id,module_path,name,description,
       source_host,source_repository,path,latest_version,stars,created_at,updated_at
FROM ranked
WHERE result_ordinal<=CASE WHEN requested_module_path<>'' THEN 1 ELSE $1::bigint END
ORDER BY ordinal,result_ordinal
`

type FindExactLocalizedSkillsBatchParams struct {
	PageLimit   int64    `json:"page_limit"`
	QueryIds    []string `json:"query_ids"`
	Queries     []string `json:"queries"`
	ModulePaths []string `json:"module_paths"`
	Locale      string   `json:"locale"`
}

type FindExactLocalizedSkillsBatchRow struct {
	QueryID             string    `json:"query_id"`
	Query               string    `json:"query"`
	RequestedModulePath string    `json:"requested_module_path"`
	ID                  int64     `json:"id"`
	ModuleID            int64     `json:"module_id"`
	ModulePath          string    `json:"module_path"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	SourceHost          string    `json:"source_host"`
	SourceRepository    string    `json:"source_repository"`
	Path                string    `json:"path"`
	LatestVersion       string    `json:"latest_version"`
	Stars               int64     `json:"stars"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) FindExactLocalizedSkillsBatch(ctx context.Context, arg FindExactLocalizedSkillsBatchParams) ([]FindExactLocalizedSkillsBatchRow, error) {
	rows, err := q.db.Query(ctx, findExactLocalizedSkillsBatch,
		arg.PageLimit,
		arg.QueryIds,
		arg.Queries,
		arg.ModulePaths,
		arg.Locale,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindExactLocalizedSkillsBatchRow{}
	for rows.Next() {
		var i FindExactLocalizedSkillsBatchRow
		if err := rows.Scan(
			&i.QueryID,
			&i.Query,
			&i.RequestedModulePath,
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLocalizedSkillsBatch = `-- name: FindLocalizedSkillsBatch :many
WITH requested AS (
    SELECT ids.id AS query_id, queries.query, module_paths.module_path, exact_names.exact_name, ids.ordinal
    FROM unnest($3::text[]) WITH ORDINALITY AS ids(id, ordinal)
    JOIN unnest($4::text[]) WITH ORDINALITY AS queries(query, ordinal) USING (ordinal)
    JOIN unnest($5::text[]) WITH ORDINALITY AS module_paths(module_path, ordinal) USING (ordinal)
    JOIN unnest($6::boolean[]) WITH ORDINALITY AS exact_names(exact_name, ordinal) USING (ordinal)
)
SELECT input.query_id::text AS query_id,input.query::text AS query,input.module_path::text AS requested_module_path,
       result.id,result.module_id,result.module_path,result.name,result.description,
       result.source_host,result.source_repository,result.path,result.latest_version,result.stars,
       result.created_at,result.updated_at
FROM requested input
JOIN LATERAL (
    SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
           mvs.name, COALESCE(ls.description,mvs.description) AS description,
           m.source_host, m.source_path AS source_repository, mvs.path,
           mv.version AS latest_version, m.stars,
           mv.created_at, m.updated_at,
           CASE
               WHEN lower(mvs.name)=lower(input.query) THEN 0
               WHEN lower(mvs.name) LIKE lower(input.query) || '%' THEN 1
               WHEN lower(mvs.name) LIKE '%' || lower(input.query) || '%' THEN 2
               WHEN lower(m.path)=lower(input.query) THEN 3
               WHEN lower(m.path) LIKE '%' || lower(input.query) || '%' THEN 4
               ELSE 5
           END AS sort_tier,
           similarity(mvs.name,input.query) AS name_similarity
    FROM modules m
    JOIN versions mv ON mv.id=m.current_version_id
    JOIN skills mvs ON mvs.version_id=mv.id
    LEFT JOIN localized_descriptions ls
      ON ls.resource_kind='skill' AND ls.resource_id=m.path || ':' || mvs.name AND ls.locale=$1
    LEFT JOIN localized_descriptions lm
      ON lm.resource_kind='module' AND lm.resource_id=m.path AND lm.locale=$1
    WHERE (
        input.module_path<>'' AND m.path=input.module_path AND mvs.name=input.query
    ) OR (
        input.module_path='' AND (
            (input.exact_name AND lower(mvs.name)=lower(input.query))
            OR (NOT input.exact_name AND (
                lower(mvs.name) LIKE '%' || lower(input.query) || '%'
                OR lower(mvs.description) LIKE '%' || lower(input.query) || '%'
                OR lower(m.path) LIKE '%' || lower(input.query) || '%'
                OR lower(COALESCE(ls.description,'')) LIKE '%' || lower(input.query) || '%'
                OR lower(COALESCE(lm.description,'')) LIKE '%' || lower(input.query) || '%'
            ))
        )
    )
    ORDER BY sort_tier,name_similarity DESC,m.path,mvs.path
    LIMIT CASE WHEN input.module_path<>'' THEN 1 ELSE $2::int END
) result ON true
ORDER BY input.ordinal,result.sort_tier,result.name_similarity DESC,
         result.module_path,result.path
`

type FindLocalizedSkillsBatchParams struct {
	Locale      string   `json:"locale"`
	PageLimit   int32    `json:"page_limit"`
	QueryIds    []string `json:"query_ids"`
	Queries     []string `json:"queries"`
	ModulePaths []string `json:"module_paths"`
	ExactNames  []bool   `json:"exact_names"`
}

type FindLocalizedSkillsBatchRow struct {
	QueryID             string    `json:"query_id"`
	Query               string    `json:"query"`
	RequestedModulePath string    `json:"requested_module_path"`
	ID                  int64     `json:"id"`
	ModuleID            int64     `json:"module_id"`
	ModulePath          string    `json:"module_path"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	SourceHost          string    `json:"source_host"`
	SourceRepository    string    `json:"source_repository"`
	Path                string    `json:"path"`
	LatestVersion       string    `json:"latest_version"`
	Stars               int64     `json:"stars"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) FindLocalizedSkillsBatch(ctx context.Context, arg FindLocalizedSkillsBatchParams) ([]FindLocalizedSkillsBatchRow, error) {
	rows, err := q.db.Query(ctx, findLocalizedSkillsBatch,
		arg.Locale,
		arg.PageLimit,
		arg.QueryIds,
		arg.Queries,
		arg.ModulePaths,
		arg.ExactNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindLocalizedSkillsBatchRow{}
	for rows.Next() {
		var i FindLocalizedSkillsBatchRow
		if err := rows.Scan(
			&i.QueryID,
			&i.Query,
			&i.RequestedModulePath,
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBackfillRun = `-- name: InsertBackfillRun :exec
INSERT INTO module_backfill_runs (id,module_path,status,error_count,diagnostics,created_at,updated_at)
VALUES ($1,$2,$3,0,$4,$5,$5)
`

type InsertBackfillRunParams struct {
	ID          string          `json:"id"`
	ModulePath  string          `json:"module_path"`
	Status      string          `json:"status"`
	Diagnostics json.RawMessage `json:"diagnostics"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) InsertBackfillRun(ctx context.Context, arg InsertBackfillRunParams) error {
	_, err := q.db.Exec(ctx, insertBackfillRun,
		arg.ID,
		arg.ModulePath,
		arg.Status,
		arg.Diagnostics,
		arg.CreatedAt,
	)
	return err
}

const insertModuleVersion = `-- name: InsertModuleVersion :one
INSERT INTO versions (module_id, version, ref, commit_sha, tree_sha, sum, archive_size, commit_time, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id
`

type InsertModuleVersionParams struct {
	ModuleID    int64     `json:"module_id"`
	Version     string    `json:"version"`
	Ref         string    `json:"ref"`
	CommitSha   string    `json:"commit_sha"`
	TreeSha     string    `json:"tree_sha"`
	Sum         string    `json:"sum"`
	ArchiveSize int64     `json:"archive_size"`
	CommitTime  time.Time `json:"commit_time"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertModuleVersion(ctx context.Context, arg InsertModuleVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertModuleVersion,
		arg.ModuleID,
		arg.Version,
		arg.Ref,
		arg.CommitSha,
		arg.TreeSha,
		arg.Sum,
		arg.ArchiveSize,
		arg.CommitTime,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSkill = `-- name: InsertSkill :exec
INSERT INTO skills (
    version_id, name, path, description
) VALUES ($1,$2,$3,$4)
`

type InsertSkillParams struct {
	VersionID   int64  `json:"version_id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Description string `json:"description"`
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) error {
	_, err := q.db.Exec(ctx, insertSkill,
		arg.VersionID,
		arg.Name,
		arg.Path,
		arg.Description,
	)
	return err
}

const latestBackfillRun = `-- name: LatestBackfillRun :one
SELECT id, module_path, status, started_at, completed_at, error_count, diagnostics, created_at, updated_at FROM module_backfill_runs WHERE module_path=$1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestBackfillRun(ctx context.Context, modulePath string) (ModuleBackfillRun, error) {
	row := q.db.QueryRow(ctx, latestBackfillRun, modulePath)
	var i ModuleBackfillRun
	err := row.Scan(
		&i.ID,
		&i.ModulePath,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCount,
		&i.Diagnostics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
       mvs.name, mvs.description, m.source_host,
       m.source_path AS source_repository, mvs.path,
       mv.version AS latest_version, m.stars,
       mv.created_at, m.updated_at
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
ORDER BY mvs.name,m.path,mvs.path
LIMIT $1 OFFSET $2
`

type ListSkillsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSkillsRow struct {
	ID               int64     `json:"id"`
	ModuleID         int64     `json:"module_id"`
	ModulePath       string    `json:"module_path"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	SourceHost       string    `json:"source_host"`
	SourceRepository string    `json:"source_repository"`
	Path             string    `json:"path"`
	LatestVersion    string    `json:"latest_version"`
	Stars            int64     `json:"stars"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsRow{}
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const localizedDescription = `-- name: LocalizedDescription :one
SELECT description FROM localized_descriptions
WHERE resource_kind=$1 AND resource_id=$2 AND locale=$3
`

type LocalizedDescriptionParams struct {
	ResourceKind string `json:"resource_kind"`
	ResourceID   string `json:"resource_id"`
	Locale       string `json:"locale"`
}

func (q *Queries) LocalizedDescription(ctx context.Context, arg LocalizedDescriptionParams) (string, error) {
	row := q.db.QueryRow(ctx, localizedDescription, arg.ResourceKind, arg.ResourceID, arg.Locale)
	var description string
	err := row.Scan(&description)
	return description, err
}

const moduleByPath = `-- name: ModuleByPath :one
SELECT id, source_host, source_path, path, current_version_id, description, stars, source_etag, source_checked_at, source_retry_at, created_at, updated_at FROM modules WHERE path = $1
`

func (q *Queries) ModuleByPath(ctx context.Context, modulePath string) (Module, error) {
	row := q.db.QueryRow(ctx, moduleByPath, modulePath)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.SourceHost,
		&i.SourcePath,
		&i.Path,
		&i.CurrentVersionID,
		&i.Description,
		&i.Stars,
		&i.SourceEtag,
		&i.SourceCheckedAt,
		&i.SourceRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const modulePublicationCommit = `-- name: ModulePublicationCommit :one
SELECT mv.commit_sha
FROM versions mv
JOIN modules m ON m.id=mv.module_id
WHERE m.path=$1 AND mv.version=$2
`

type ModulePublicationCommitParams struct {
	ModulePath string `json:"module_path"`
	Version    string `json:"version"`
}

func (q *Queries) ModulePublicationCommit(ctx context.Context, arg ModulePublicationCommitParams) (string, error) {
	row := q.db.QueryRow(ctx, modulePublicationCommit, arg.ModulePath, arg.Version)
	var commit_sha string
	err := row.Scan(&commit_sha)
	return commit_sha, err
}

const moduleVersion = `-- name: ModuleVersion :one
SELECT mv.id, mv.module_id, mv.version, mv.ref, mv.commit_sha, mv.tree_sha,
       mv.sum, mv.archive_size, mv.commit_time, mv.created_at
FROM versions mv
JOIN modules m ON m.id=mv.module_id
WHERE m.path=$1 AND mv.version=$2
`

type ModuleVersionParams struct {
	ModulePath string `json:"module_path"`
	Version    string `json:"version"`
}

func (q *Queries) ModuleVersion(ctx context.Context, arg ModuleVersionParams) (Version, error) {
	row := q.db.QueryRow(ctx, moduleVersion, arg.ModulePath, arg.Version)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.Ref,
		&i.CommitSha,
		&i.TreeSha,
		&i.Sum,
		&i.ArchiveSize,
		&i.CommitTime,
		&i.CreatedAt,
	)
	return i, err
}

const moduleVersionCount = `-- name: ModuleVersionCount :one
SELECT COUNT(*)
FROM versions mv
JOIN modules m ON m.id=mv.module_id
WHERE m.path=$1 AND mv.version=$2
`

type ModuleVersionCountParams struct {
	ModulePath string `json:"module_path"`
	Version    string `json:"version"`
}

func (q *Queries) ModuleVersionCount(ctx context.Context, arg ModuleVersionCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, moduleVersionCount, arg.ModulePath, arg.Version)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchLocalizedSkills = `-- name: SearchLocalizedSkills :many
SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
       mvs.name, COALESCE(ls.description,mvs.description) AS description,
       m.source_host, m.source_path AS source_repository, mvs.path,
       mv.version AS latest_version, m.stars,
       mv.created_at, m.updated_at
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
LEFT JOIN localized_descriptions ls
  ON ls.resource_kind='skill' AND ls.resource_id=m.path || ':' || mvs.name AND ls.locale=$1
LEFT JOIN localized_descriptions lm
  ON lm.resource_kind='module' AND lm.resource_id=m.path AND lm.locale=$1
WHERE ($2::boolean AND lower(mvs.name)=lower($3))
OR (NOT $2::boolean AND (
    lower(mvs.name) LIKE '%' || lower($3) || '%'
    OR lower(mvs.description) LIKE '%' || lower($3) || '%'
    OR lower(m.path) LIKE '%' || lower($3) || '%'
    OR lower(COALESCE(ls.description,'')) LIKE '%' || lower($3) || '%'
    OR lower(COALESCE(lm.description,'')) LIKE '%' || lower($3) || '%'
))
ORDER BY CASE
    WHEN lower(mvs.name)=lower($3) THEN 0
    WHEN lower(mvs.name) LIKE lower($3) || '%' THEN 1
    WHEN lower(mvs.name) LIKE '%' || lower($3) || '%' THEN 2
    WHEN lower(m.path)=lower($3) THEN 3
    WHEN lower(m.path) LIKE '%' || lower($3) || '%' THEN 4
    ELSE 5
END,
similarity(mvs.name,$3) DESC,m.path,mvs.path
LIMIT $5 OFFSET $4
`

type SearchLocalizedSkillsParams struct {
	Locale     string `json:"locale"`
	ExactName  bool   `json:"exact_name"`
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type SearchLocalizedSkillsRow struct {
	ID               int64     `json:"id"`
	ModuleID         int64     `json:"module_id"`
	ModulePath       string    `json:"module_path"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	SourceHost       string    `json:"source_host"`
	SourceRepository string    `json:"source_repository"`
	Path             string    `json:"path"`
	LatestVersion    string    `json:"latest_version"`
	Stars            int64     `json:"stars"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) SearchLocalizedSkills(ctx context.Context, arg SearchLocalizedSkillsParams) ([]SearchLocalizedSkillsRow, error) {
	rows, err := q.db.Query(ctx, searchLocalizedSkills,
		arg.Locale,
		arg.ExactName,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchLocalizedSkillsRow{}
	for rows.Next() {
		var i SearchLocalizedSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkills = `-- name: SearchSkills :many
SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
       mvs.name, mvs.description, m.source_host,
       m.source_path AS source_repository, mvs.path,
       mv.version AS latest_version, m.stars,
       mv.created_at, m.updated_at
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
WHERE ($1::boolean AND lower(mvs.name)=lower($2))
OR (NOT $1::boolean AND
    (mvs.name || ' ' || mvs.description || ' ' || m.path) ILIKE '%' || $2 || '%')
ORDER BY CASE
    WHEN lower(mvs.name)=lower($2) THEN 0
    WHEN lower(mvs.name) LIKE lower($2) || '%' THEN 1
    WHEN lower(mvs.name) LIKE '%' || lower($2) || '%' THEN 2
    WHEN lower(m.path)=lower($2) THEN 3
    WHEN lower(m.path) LIKE '%' || lower($2) || '%' THEN 4
    ELSE 5
END,
similarity(mvs.name,$2) DESC,m.path,mvs.path
LIMIT $4 OFFSET $3
`

type SearchSkillsParams struct {
	ExactName  bool   `json:"exact_name"`
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type SearchSkillsRow struct {
	ID               int64     `json:"id"`
	ModuleID         int64     `json:"module_id"`
	ModulePath       string    `json:"module_path"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	SourceHost       string    `json:"source_host"`
	SourceRepository string    `json:"source_repository"`
	Path             string    `json:"path"`
	LatestVersion    string    `json:"latest_version"`
	Stars            int64     `json:"stars"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) SearchSkills(ctx context.Context, arg SearchSkillsParams) ([]SearchSkillsRow, error) {
	rows, err := q.db.Query(ctx, searchSkills,
		arg.ExactName,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSkillsRow{}
	for rows.Next() {
		var i SearchSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE modules SET current_version_id=$2, updated_at=$3 WHERE id=$1
`

type SetCurrentVersionParams struct {
	ID               int64       `json:"id"`
	CurrentVersionID pgtype.Int8 `json:"current_version_id"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID, arg.UpdatedAt)
	return err
}

const setCurrentVersionByCoordinate = `-- name: SetCurrentVersionByCoordinate :exec
UPDATE modules AS target
SET current_version_id=(
    SELECT id FROM versions
    WHERE versions.module_id=target.id AND version=$1
), updated_at=$2
WHERE target.path=$3
`

type SetCurrentVersionByCoordinateParams struct {
	Version    string    `json:"version"`
	UpdatedAt  time.Time `json:"updated_at"`
	ModulePath string    `json:"module_path"`
}

func (q *Queries) SetCurrentVersionByCoordinate(ctx context.Context, arg SetCurrentVersionByCoordinateParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersionByCoordinate, arg.Version, arg.UpdatedAt, arg.ModulePath)
	return err
}

const skillByCoordinate = `-- name: SkillByCoordinate :one
SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
       mvs.name, mvs.description, m.source_host,
       m.source_path AS source_repository, mvs.path,
       mv.version AS latest_version, m.stars,
       mv.created_at, m.updated_at
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
WHERE m.path=$1 AND mvs.name=$2
ORDER BY mvs.path
LIMIT 1
`

type SkillByCoordinateParams struct {
	ModulePath string `json:"module_path"`
	Name       string `json:"name"`
}

type SkillByCoordinateRow struct {
	ID               int64     `json:"id"`
	ModuleID         int64     `json:"module_id"`
	ModulePath       string    `json:"module_path"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	SourceHost       string    `json:"source_host"`
	SourceRepository string    `json:"source_repository"`
	Path             string    `json:"path"`
	LatestVersion    string    `json:"latest_version"`
	Stars            int64     `json:"stars"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) SkillByCoordinate(ctx context.Context, arg SkillByCoordinateParams) (SkillByCoordinateRow, error) {
	row := q.db.QueryRow(ctx, skillByCoordinate, arg.ModulePath, arg.Name)
	var i SkillByCoordinateRow
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.ModulePath,
		&i.Name,
		&i.Description,
		&i.SourceHost,
		&i.SourceRepository,
		&i.Path,
		&i.LatestVersion,
		&i.Stars,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skillPublishedVersions = `-- name: SkillPublishedVersions :many
SELECT DISTINCT mv.version
FROM modules m
JOIN versions mv ON mv.module_id=m.id
JOIN skills mvs ON mvs.version_id=mv.id
WHERE m.path=$1 AND mvs.name=$2
ORDER BY mv.version
`

type SkillPublishedVersionsParams struct {
	ModulePath string `json:"module_path"`
	Name       string `json:"name"`
}

func (q *Queries) SkillPublishedVersions(ctx context.Context, arg SkillPublishedVersionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, skillPublishedVersions, arg.ModulePath, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skills = `-- name: Skills :many
SELECT mvs.version_id, mvs.name, mv.version, mv.commit_sha,
       mvs.path, mv.commit_time, mvs.description
FROM modules m
JOIN versions mv ON mv.module_id=m.id
JOIN skills mvs ON mvs.version_id=mv.id
WHERE m.path=$1 AND mv.version=$2
ORDER BY mvs.path
`

type SkillsParams struct {
	ModulePath string `json:"module_path"`
	Version    string `json:"version"`
}

type SkillsRow struct {
	VersionID   int64     `json:"version_id"`
	Name        string    `json:"name"`
	Version     string    `json:"version"`
	CommitSha   string    `json:"commit_sha"`
	Path        string    `json:"path"`
	CommitTime  time.Time `json:"commit_time"`
	Description string    `json:"description"`
}

func (q *Queries) Skills(ctx context.Context, arg SkillsParams) ([]SkillsRow, error) {
	rows, err := q.db.Query(ctx, skills, arg.ModulePath, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillsRow{}
	for rows.Next() {
		var i SkillsRow
		if err := rows.Scan(
			&i.VersionID,
			&i.Name,
			&i.Version,
			&i.CommitSha,
			&i.Path,
			&i.CommitTime,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillsByCoordinates = `-- name: SkillsByCoordinates :many
WITH requested AS (
    SELECT module_paths.module_path, skill_names.name, module_paths.ordinal
    FROM unnest($1::text[]) WITH ORDINALITY AS module_paths(module_path, ordinal)
    JOIN unnest($2::text[]) WITH ORDINALITY AS skill_names(name, ordinal) USING (ordinal)
)
SELECT mvs.version_id AS id, mv.module_id, m.path AS module_path,
       mvs.name, mvs.description, m.source_host,
       m.source_path AS source_repository, mvs.path,
       mv.version AS latest_version, m.stars,
       mv.created_at, m.updated_at
FROM requested input
JOIN modules m ON m.path=input.module_path
JOIN versions mv ON mv.id=m.current_version_id
JOIN LATERAL (
    SELECT candidate.id, candidate.version_id, candidate.name, candidate.path, candidate.description
    FROM skills candidate
    WHERE candidate.version_id=mv.id AND candidate.name=input.name
    ORDER BY candidate.path
    LIMIT 1
) mvs ON true
ORDER BY input.ordinal
`

type SkillsByCoordinatesParams struct {
	ModulePaths []string `json:"module_paths"`
	Names       []string `json:"names"`
}

type SkillsByCoordinatesRow struct {
	ID               int64     `json:"id"`
	ModuleID         int64     `json:"module_id"`
	ModulePath       string    `json:"module_path"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	SourceHost       string    `json:"source_host"`
	SourceRepository string    `json:"source_repository"`
	Path             string    `json:"path"`
	LatestVersion    string    `json:"latest_version"`
	Stars            int64     `json:"stars"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) SkillsByCoordinates(ctx context.Context, arg SkillsByCoordinatesParams) ([]SkillsByCoordinatesRow, error) {
	rows, err := q.db.Query(ctx, skillsByCoordinates, arg.ModulePaths, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillsByCoordinatesRow{}
	for rows.Next() {
		var i SkillsByCoordinatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.ModulePath,
			&i.Name,
			&i.Description,
			&i.SourceHost,
			&i.SourceRepository,
			&i.Path,
			&i.LatestVersion,
			&i.Stars,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleQueuedBackfillRuns = `-- name: StaleQueuedBackfillRuns :many
SELECT id, module_path, status, started_at, completed_at, error_count, diagnostics, created_at, updated_at FROM module_backfill_runs WHERE status='queued' AND updated_at<$1 ORDER BY updated_at LIMIT $2
`

type StaleQueuedBackfillRunsParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) StaleQueuedBackfillRuns(ctx context.Context, arg StaleQueuedBackfillRunsParams) ([]ModuleBackfillRun, error) {
	rows, err := q.db.Query(ctx, staleQueuedBackfillRuns, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleBackfillRun{}
	for rows.Next() {
		var i ModuleBackfillRun
		if err := rows.Scan(
			&i.ID,
			&i.ModulePath,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorCount,
			&i.Diagnostics,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBackfillRun = `-- name: StartBackfillRun :execrows
UPDATE module_backfill_runs SET status='running',started_at=COALESCE(started_at,$1),updated_at=$1
WHERE id=$2 AND status='queued'
`

type StartBackfillRunParams struct {
	Now time.Time `json:"now"`
	ID  string    `json:"id"`
}

func (q *Queries) StartBackfillRun(ctx context.Context, arg StartBackfillRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, startBackfillRun, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchBackfillRun = `-- name: TouchBackfillRun :execrows
UPDATE module_backfill_runs SET updated_at=$2 WHERE id=$1 AND status='running'
`

type TouchBackfillRunParams struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) TouchBackfillRun(ctx context.Context, arg TouchBackfillRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchBackfillRun, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const translationCandidates = `-- name: TranslationCandidates :many
SELECT 'module'::text AS resource_kind, m.path AS resource_id, m.description,
       COALESCE(ld.source_digest, '') AS source_digest,
       COALESCE(ld.prompt_version, '') AS prompt_version
FROM modules m
LEFT JOIN localized_descriptions ld
  ON ld.resource_kind='module' AND ld.resource_id=m.path AND ld.locale=$1
WHERE trim(m.description)<>''
UNION ALL
SELECT 'skill'::text, m.path || ':' || mvs.name, mvs.description,
       COALESCE(ld.source_digest, ''), COALESCE(ld.prompt_version, '')
FROM modules m
JOIN versions mv ON mv.id=m.current_version_id
JOIN skills mvs ON mvs.version_id=mv.id
LEFT JOIN localized_descriptions ld
  ON ld.resource_kind='skill' AND ld.resource_id=m.path || ':' || mvs.name AND ld.locale=$1
WHERE trim(mvs.description)<>''
  AND mvs.path=(
      SELECT min(candidate.path)
      FROM skills candidate
      WHERE candidate.version_id=mv.id AND candidate.name=mvs.name
  )
ORDER BY resource_kind, resource_id
`

type TranslationCandidatesRow struct {
	ResourceKind  string `json:"resource_kind"`
	ResourceID    string `json:"resource_id"`
	Description   string `json:"description"`
	SourceDigest  string `json:"source_digest"`
	PromptVersion string `json:"prompt_version"`
}

func (q *Queries) TranslationCandidates(ctx context.Context, locale string) ([]TranslationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, translationCandidates, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationCandidatesRow{}
	for rows.Next() {
		var i TranslationCandidatesRow
		if err := rows.Scan(
			&i.ResourceKind,
			&i.ResourceID,
			&i.Description,
			&i.SourceDigest,
			&i.PromptVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModuleSourceMetadata = `-- name: UpdateModuleSourceMetadata :execrows
UPDATE modules SET description = $1, stars = $2, source_etag = $3,
source_checked_at = COALESCE($4, source_checked_at), source_retry_at = $5,
updated_at = CURRENT_TIMESTAMP WHERE path = $6
`

type UpdateModuleSourceMetadataParams struct {
	Description     string      `json:"description"`
	Stars           int64       `json:"stars"`
	SourceEtag      pgtype.Text `json:"source_etag"`
	SourceCheckedAt *time.Time  `json:"source_checked_at"`
	SourceRetryAt   *time.Time  `json:"source_retry_at"`
	ModulePath      string      `json:"module_path"`
}

func (q *Queries) UpdateModuleSourceMetadata(ctx context.Context, arg UpdateModuleSourceMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModuleSourceMetadata,
		arg.Description,
		arg.Stars,
		arg.SourceEtag,
		arg.SourceCheckedAt,
		arg.SourceRetryAt,
		arg.ModulePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLocalizedDescription = `-- name: UpsertLocalizedDescription :exec
INSERT INTO localized_descriptions (resource_kind,resource_id,locale,description,source_digest,prompt_version,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$7)
ON CONFLICT(resource_kind,resource_id,locale) DO UPDATE SET
description=excluded.description,source_digest=excluded.source_digest,
prompt_version=excluded.prompt_version,updated_at=excluded.updated_at
`

type UpsertLocalizedDescriptionParams struct {
	ResourceKind  string    `json:"resource_kind"`
	ResourceID    string    `json:"resource_id"`
	Locale        string    `json:"locale"`
	Description   string    `json:"description"`
	SourceDigest  string    `json:"source_digest"`
	PromptVersion string    `json:"prompt_version"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) UpsertLocalizedDescription(ctx context.Context, arg UpsertLocalizedDescriptionParams) error {
	_, err := q.db.Exec(ctx, upsertLocalizedDescription,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Locale,
		arg.Description,
		arg.SourceDigest,
		arg.PromptVersion,
		arg.CreatedAt,
	)
	return err
}

const upsertModule = `-- name: UpsertModule :one

INSERT INTO modules (source_host, source_path, path, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (path) DO UPDATE SET updated_at = excluded.updated_at
RETURNING id, source_host, source_path, path, current_version_id, description, stars, source_etag, source_checked_at, source_retry_at, created_at, updated_at
`

type UpsertModuleParams struct {
	SourceHost string    `json:"source_host"`
	SourcePath string    `json:"source_path"`
	Path       string    `json:"path"`
	CreatedAt  time.Time `json:"created_at"`
}

// [INPUT]: Depends on the reviewed PostgreSQL Module Catalog schema and sqlc's pgx/v5 generator.
// [OUTPUT]: Defines typed Module, immutable Module Version Skill, localization, search, and Backfill persistence operations.
// [POS]: Serves as the single maintained query source for the Hub Catalog module.
// [PROTOCOL]: Update this header when this file changes, then review AGENTS.md
func (q *Queries) UpsertModule(ctx context.Context, arg UpsertModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, upsertModule,
		arg.SourceHost,
		arg.SourcePath,
		arg.Path,
		arg.CreatedAt,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.SourceHost,
		&i.SourcePath,
		&i.Path,
		&i.CurrentVersionID,
		&i.Description,
		&i.Stars,
		&i.SourceEtag,
		&i.SourceCheckedAt,
		&i.SourceRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
