// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Localization struct {
	ResourceKind  string      `json:"resource_kind"`
	SourceDigest  string      `json:"source_digest"`
	Lang          string      `json:"lang"`
	ResultKind    string      `json:"result_kind"`
	TextContent   pgtype.Text `json:"text_content"`
	ErrorKind     pgtype.Text `json:"error_kind"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	PromptVersion string      `json:"prompt_version"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

// Canonical Skill Packages and mutable source/discovery state.
type Package struct {
	ID int64 `json:"id"`
	// Source host derived from Package Path, for example github.com.
	SourceHost string `json:"source_host"`
	// Host-relative source path derived from Package Path, for example acme/skills.
	SourcePath string `json:"source_path"`
	// Canonical globally unique Package Path.
	Path string `json:"path"`
	// Current discovery-visible Version; constrained to belong to this Package.
	CurrentVersionID pgtype.Int8 `json:"current_version_id"`
	// Mutable source description used by discovery.
	Description       string `json:"description"`
	DescriptionDigest string `json:"description_digest"`
	// Mutable source popularity count used by discovery.
	Stars int64 `json:"stars"`
	// Conditional-request token for source enrichment.
	SourceEtag pgtype.Text `json:"source_etag"`
	// Last successful source enrichment check.
	SourceCheckedAt *time.Time `json:"source_checked_at"`
	// Earliest source enrichment retry after upstream throttling.
	SourceRetryAt *time.Time `json:"source_retry_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type PackageBackfillRun struct {
	ID             string      `json:"id"`
	PackagePath    string      `json:"package_path"`
	Status         string      `json:"status"`
	StartedAt      *time.Time  `json:"started_at"`
	CompletedAt    *time.Time  `json:"completed_at"`
	PublishedCount int32       `json:"published_count"`
	SkippedCount   int32       `json:"skipped_count"`
	RejectedCount  int32       `json:"rejected_count"`
	FailedCount    int32       `json:"failed_count"`
	FailureCode    pgtype.Text `json:"failure_code"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type PackageBackfillVersionOutcome struct {
	RunID        string      `json:"run_id"`
	Version      string      `json:"version"`
	CommitSha    string      `json:"commit_sha"`
	Outcome      string      `json:"outcome"`
	ReasonCode   pgtype.Text `json:"reason_code"`
	AttemptCount int32       `json:"attempt_count"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

// Skill members contained by one immutable Package Version.
type Skill struct {
	ID        int64 `json:"id"`
	VersionID int64 `json:"version_id"`
	// Canonical Skill name read from SKILL.md.
	Name string `json:"name"`
	// Package-relative directory containing SKILL.md; unique within the Version.
	Path string `json:"path"`
	// Searchable Skill description read from SKILL.md.
	Description       string `json:"description"`
	DescriptionDigest string `json:"description_digest"`
	DocumentDigest    string `json:"document_digest"`
	// Detected BCP 47 source language for the immutable SKILL.md document; empty when undetermined or mixed.
	SourceLanguage string `json:"source_language"`
}

// Immutable published versions owned by Packages.
type Version struct {
	ID        int64 `json:"id"`
	PackageID int64 `json:"package_id"`
	// Canonical immutable Package Version.
	Version string `json:"version"`
	// Source ref resolved when the Version was published.
	Ref string `json:"ref"`
	// Source commit captured by this Version.
	CommitSha string `json:"commit_sha"`
	// Package root tree captured by this Version.
	TreeSha string `json:"tree_sha"`
	// Version-independent h1 checksum of the normalized Package Artifact tree.
	ContentSum string `json:"content_sum"`
	// Direct effective Version whose Package content is identical; NULL when this Version owns an Artifact.
	EquivalentVersion pgtype.Text `json:"equivalent_version"`
	// Canonical coordinate-bound h1 checksum of the normalized Package Artifact tree.
	Sum pgtype.Text `json:"sum"`
	// Source commit time exposed as Package Info time.
	CommitTime time.Time `json:"commit_time"`
	CreatedAt  time.Time `json:"created_at"`
}
